// ── Markdown report generator ────────────────────────────────

const CATEGORY_LABELS = {
  files: 'Exposed Files',
  headers: 'Security Headers',
  robots: 'Robots & Sitemap',
  seo: 'SEO Basics',
  endpoints: 'API Endpoints',
  fuzz: 'Endpoint Fuzzing',
  leakage: 'Information Leakage',
};

const SEVERITY_ICONS = {
  critical: '[CRITICAL]',
  warning: '[WARNING]',
  info: '[INFO]',
  pass: '[PASS]',
};

export function generateReport(results) {
  const lines = [];
  const date = new Date(results.timestamp).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  lines.push('# Lockdown Security Report');
  lines.push('');
  lines.push(`**Target:** ${results.url}`);
  lines.push(`**Date:** ${date}`);
  lines.push('');

  // Summary
  const allFindings = Object.values(results.categories).flat();
  const critCount = allFindings.filter(f => f.severity === 'critical').length;
  const warnCount = allFindings.filter(f => f.severity === 'warning').length;
  const infoCount = allFindings.filter(f => f.severity === 'info').length;
  const passCount = allFindings.filter(f => f.severity === 'pass').length;

  lines.push('## Summary');
  lines.push('');
  lines.push(`| Severity | Count |`);
  lines.push(`|----------|-------|`);
  lines.push(`| Critical | ${critCount} |`);
  lines.push(`| Warning  | ${warnCount} |`);
  lines.push(`| Info     | ${infoCount} |`);
  lines.push(`| Pass     | ${passCount} |`);
  lines.push('');

  const total = allFindings.length || 1;
  const score = Math.max(0, Math.round(((passCount - critCount * 3 - warnCount) / total) * 100));
  const grade = score >= 80 ? 'A' : score >= 60 ? 'B' : score >= 40 ? 'C' : score >= 20 ? 'D' : 'F';
  lines.push(`**Grade: ${grade}** (${score}/100)`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Categories
  for (const [key, findings] of Object.entries(results.categories)) {
    if (!findings.length) continue;
    const label = CATEGORY_LABELS[key] || key;
    lines.push(`## ${label}`);
    lines.push('');

    for (const f of findings) {
      const icon = SEVERITY_ICONS[f.severity] || '';
      lines.push(`### ${icon} ${f.title}`);
      if (f.endpoint) {
        lines.push(`**Endpoint:** \`${f.endpoint}\``);
      }
      if (f.detail) {
        lines.push('');
        lines.push(f.detail);
      }
      if (f.hardening) {
        lines.push('');
        lines.push(`> **Hardening:** ${f.hardening}`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // Network log
  const requests = results.requests || [];
  if (requests.length) {
    lines.push('## Network Log');
    lines.push('');
    lines.push(`${requests.length} HTTP requests made during scan.`);
    lines.push('');
    lines.push('| Method | URL | Status | Size | Time |');
    lines.push('|--------|-----|--------|------|------|');
    for (const req of requests) {
      const url = req.url.length > 60 ? req.url.substring(0, 57) + '...' : req.url;
      const size = req.size === null ? '-' : req.size < 1024 ? req.size + ' B' : (req.size / 1024).toFixed(1) + ' KB';
      lines.push(`| ${req.method} | \`${url}\` | ${req.status ?? 'TIMEOUT'} | ${size} | ${req.duration}ms |`);
    }
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  lines.push('*Report generated by [Lockdown](https://lockdown.neorgon.com/) — Part of Neorgon*');

  return lines.join('\n');
}
