// ── Export ───────────────────────────────────────────────────
// The deliverable. Three artifacts that agree with each other: the
// model, the pictures, and the prose. The open questions from the
// readiness check ride inside the brief, so whoever builds this knows
// where the design stopped and guessing would begin.

import { MODEL_VERSION, slug, zoneKind, fieldType } from './model.js';
import { runChecks } from './lint.js';
import { drawBoard, drawCard, toBlob } from './image.js';
import { makeZip } from './zip.js';

const enc = new TextEncoder();
const bytes = (str) => enc.encode(str);

/* ── game.json ────────────────────────────────────────────── */

export function buildJson(d) {
  return `${JSON.stringify({ ...d, boardwright: MODEL_VERSION }, null, 2)}\n`;
}

/* ── BRIEF.md ─────────────────────────────────────────────── */

export function buildBrief(d, findings = runChecks(d)) {
  const name = d.meta.name || 'Untitled game';
  const zoneName = (id) => d.board.zones.find((z) => z.id === id)?.name || '(none)';
  const phaseName = (id) => d.phases.find((p) => p.id === id)?.name || 'any phase';
  // An action may legitimately have only one end: a marker that appears on a
  // track comes from nowhere the board models.
  const move = (a) => {
    if (a.from && a.to) return `${zoneName(a.from)} to ${zoneName(a.to)}`;
    if (a.to) return `into ${zoneName(a.to)}`;
    if (a.from) return `out of ${zoneName(a.from)}`;
    return 'no movement declared';
  };
  const holds = (z) => z.accepts.map((a) =>
    d.templates.find((t) => t.id === a)?.name || d.components.find((c) => c.id === a)?.name || a).join(', ') || '(none)';

  const L = [];
  L.push(`# ${name}: implementation brief`, '');
  if (d.meta.tagline) L.push(`> ${d.meta.tagline}`, '');
  L.push(`${d.meta.minPlayers}-${d.meta.maxPlayers} players · about ${d.meta.playtime} minutes`);
  L.push(`Generated by Boardwright on ${new Date().toISOString().slice(0, 10)} · model version ${MODEL_VERSION}`, '');

  L.push('## What to build', '');
  L.push('Two deliverables: a UI that matches `board.png`, and an engine that enforces the rules below.');
  L.push('`game.json` is the source of truth. Everything in this file is the same data written for a person to read, so where they disagree, trust the JSON.', '');

  L.push('## Files in this bundle', '');
  L.push('| File | What it is |', '| --- | --- |');
  L.push('| `game.json` | The model. Zones are containers, actions are the legal moves. |');
  L.push(`| \`board.png\` | Board reference, ${d.board.width}x${d.board.height} units. Every rectangle is labelled with its zone id. |`);
  d.templates.forEach((t) => {
    const base = slug(t.name, t.id);
    L.push(`| \`cards/${base}-design.png\` | Design sheet for "${t.name}". Dashed boxes are slots, labelled with their key. |`);
    if (t.variants.length) {
      L.push(`| \`cards/${base}-*.png\` | Print faces, one per deck colour: ${t.variants.map((v) => slug(v.name, v.id)).join(', ')}. No annotations. |`);
    } else {
      L.push(`| \`cards/${base}-face.png\` | Print face for "${t.name}". No annotations. |`);
    }
  });
  L.push('| `BRIEF.md` | This file. |', '');

  L.push('## Suggested state shape', '');
  L.push('```json');
  L.push(JSON.stringify(stateShape(d), null, 2));
  L.push('```', '');
  L.push('Zones marked *per player* are instantiated once per seat. Shared zones exist once for the table.', '');

  /* Zones */
  L.push('## Board zones', '');
  if (!d.board.zones.length) {
    L.push('_None defined._', '');
  } else {
    L.push(`Positions are in board units, origin top-left, board ${d.board.width}x${d.board.height}.`, '');
    L.push('| id | name | kind | owner | visible to | capacity | holds | x, y, w, h |');
    L.push('| --- | --- | --- | --- | --- | --- | --- | --- |');
    d.board.zones.forEach((z) => L.push(row([
      `\`${z.id}\``, z.name, zoneKind(z.kind).label, z.owner,
      z.visibility, z.capacity ?? 'unlimited', holds(z),
      `${z.x}, ${z.y}, ${z.w}, ${z.h}`,
    ])));
    L.push('');
    const noted = d.board.zones.filter((z) => z.notes.trim());
    if (noted.length) {
      L.push('Zone notes:', '');
      noted.forEach((z) => L.push(`- **${z.name}**: ${inline(z.notes)}`));
      L.push('');
    }
  }

  /* Components */
  L.push('## Components', '');
  if (!d.components.length) {
    L.push('_None declared._', '');
  } else {
    L.push('| id | name | kind | count |', '| --- | --- | --- | --- |');
    d.components.forEach((c) => L.push(row([
      `\`${c.id}\``, c.name, c.kind, c.perPlayer ? `${c.count} per player` : String(c.count),
    ])));
    L.push('');
  }

  /* Cards */
  L.push('## Card templates', '');
  if (!d.templates.length) {
    L.push('_This game has no cards._', '');
  } else {
    d.templates.forEach((t) => {
      L.push(`### ${t.name} \`${t.id}\``, '');
      L.push(`${t.w}x${t.h}mm, ${t.count} copies, ${t.corner}mm corner radius. Slot rectangles are percentages of the face.`, '');
      L.push(`Face \`${t.bg}\`, ink \`${t.ink}\`, accent \`${t.accent}\`. Frame: ${t.frame}.${t.border ? ' Keyline border on.' : ''}`, '');
      if (t.notes.trim()) L.push(inline(t.notes), '');

      if (t.variants.length) {
        L.push(`This template prints as ${t.variants.length} decks that share every slot and differ only in paint:`, '');
        L.push('| deck | key | face | ink | mark |', '| --- | --- | --- | --- | --- |');
        t.variants.forEach((v) => L.push(row([v.name, `\`${slug(v.name, v.id)}\``, `\`${v.bg}\``, `\`${v.ink}\``, v.icon ? `glyph \`${v.icon}\`` : 'slot default'])));
        L.push('');
      }

      if (!t.fields.length) {
        L.push('_No slots defined._', '');
        return;
      }
      L.push('| slot | key | type | x% | y% | w% | h% | align | plate | value |');
      L.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |');
      t.fields.forEach((f) => {
        const glyph = f.type === 'icon' || f.type === 'pip';
        const plate = f.shape === 'none' ? '(none)' : `${f.shape}/${f.fill}${f.invert ? ' inverted' : ''}`;
        L.push(row([
          f.label, `\`${slug(f.label, f.id)}\``, fieldType(f.type).label,
          f.x, f.y, f.w, f.h, f.align, plate,
          glyph ? `glyph \`${f.icon}\`` : (f.sample || '(none)'),
        ]));
      });
      L.push('');
    });
  }

  /* Turn structure */
  L.push('## Turn structure', '');
  if (!d.phases.length) {
    L.push('_No phases defined. Treat a turn as one open action step._', '');
  } else {
    d.phases.forEach((ph, i) => {
      L.push(`${i + 1}. **${ph.name}**${ph.notes ? `: ${inline(ph.notes)}` : ''}`);
      d.actions.filter((a) => a.phase === ph.id).forEach((a) => {
        L.push(`   - ${a.name}: ${move(a)}${a.requires ? ` (requires ${inline(a.requires)})` : ''}`);
      });
    });
    L.push('');
    const loose = d.actions.filter((a) => !a.phase);
    if (loose.length) {
      L.push(`Not tied to a phase: ${loose.map((a) => a.name).join(', ')}.`, '');
    }
  }

  /* Actions */
  L.push('## Actions', '');
  if (!d.actions.length) {
    L.push('_None defined._', '');
  } else {
    L.push('| action | phase | from | to | requires | effect | limit |');
    L.push('| --- | --- | --- | --- | --- | --- | --- |');
    d.actions.forEach((a) => L.push(row([
      a.name, phaseName(a.phase), zoneName(a.from), zoneName(a.to),
      a.requires || '(none)', a.effect || '(none)', a.limit || '(none)',
    ])));
    L.push('');
  }

  /* End */
  L.push('## How the game ends', '');
  if (!d.win.length) {
    L.push('_No end condition is defined._', '');
  } else {
    d.win.forEach((w) => {
      L.push(`- **${w.name}** (${w.kind}): checked when ${inline(w.trigger) || '_unspecified_'}.${w.notes ? ` ${inline(w.notes)}` : ''}`);
    });
    L.push('');
  }

  /* Open questions */
  L.push('## Open questions', '');
  if (!findings.length) {
    L.push('The readiness check found nothing unanswered.', '');
  } else {
    L.push('The design left these open. Ask rather than guess: a wrong assumption here shows up as a rule the game does not have.', '');
    findings.forEach((f, i) => {
      L.push(`${i + 1}. **${f.question}**`);
      L.push(`   ${f.level === 'blocker' ? 'Blocking' : 'Worth confirming'} · ${f.where} · ${inline(f.detail)}`);
    });
    L.push('');
  }

  if (d.meta.notes.trim()) L.push('## Designer notes', '', inline(d.meta.notes), '');

  return `${L.join('\n')}`;
}

/** A starting shape, so the engine's state is not invented from scratch. */
function stateShape(d) {
  const perPlayer = d.board.zones.filter((z) => z.owner !== 'shared');
  const shared = d.board.zones.filter((z) => z.owner === 'shared');
  const fill = (list) => Object.fromEntries(list.map((z) => [z.id, []]));
  return {
    turn: 1,
    phase: d.phases[0]?.id || null,
    activePlayer: 0,
    players: [{ seat: 0, name: 'Player 1', zones: fill(perPlayer) }],
    zones: fill(shared),
    over: false,
    winner: null,
  };
}

const inline = (s) => String(s || '').replace(/\s*\n\s*/g, ' ').trim();
const cell = (v) => String(v ?? '').replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ').trim();
const row = (cells) => `| ${cells.map(cell).join(' | ')} |`;

/* ── Agent prompt ─────────────────────────────────────────── */

export function buildPrompt(d) {
  const name = d.meta.name || 'this board game';
  return [
    `Build a playable digital prototype of ${name} from the Boardwright bundle in this directory.`,
    '',
    '- `game.json` is the model. Zones are containers, actions are the legal moves between them, and `win` holds the end conditions.',
    '- `board.png` is the layout. Every rectangle carries the zone id used in the JSON, so you can match the picture to the model.',
    '- `cards/*.png` show each card format. Dashed boxes are slots and carry their key.',
    '- `BRIEF.md` restates all of it in prose and ends with the questions the design left open.',
    '',
    'Work in this order: the state shape in BRIEF.md, then the phases in sequence, then the actions, then the end conditions. Build the UI to match the board reference rather than inventing a layout.',
    '',
    'Where BRIEF.md lists an open question, ask me instead of choosing for me.',
  ].join('\n');
}

/* ── Bundle ───────────────────────────────────────────────── */

/**
 * @param {object} d design
 * @returns {Promise<{blob: Blob, name: string, files: {name: string, size: number}[]}>}
 */
export async function buildBundle(d) {
  const findings = runChecks(d);
  const base = slug(d.meta.name, 'boardgame');

  const boardPng = await toBlob(drawBoard(d, 1));
  const files = [
    { name: 'game.json', data: bytes(buildJson(d)) },
    { name: 'BRIEF.md', data: bytes(buildBrief(d, findings)) },
    { name: 'PROMPT.txt', data: bytes(`${buildPrompt(d)}\n`) },
    { name: 'board.png', data: new Uint8Array(await boardPng.arrayBuffer()) },
  ];

  for (const t of d.templates) {
    const base = slug(t.name, t.id);
    // Two kinds of render per deck: the design sheet carries slot keys so the
    // implementer can match rectangles to JSON, the print face carries none.
    const sheet = await toBlob(drawCard(t, 10, null, true));
    files.push({ name: `cards/${base}-design.png`, data: new Uint8Array(await sheet.arrayBuffer()) });

    const paints = t.variants.length
      ? t.variants.map((v) => ({ suffix: slug(v.name, v.id), variant: v }))
      : [{ suffix: 'face', variant: null }];
    for (const p of paints) {
      const png = await toBlob(drawCard(t, 10, p.variant, false));
      files.push({ name: `cards/${base}-${p.suffix}.png`, data: new Uint8Array(await png.arrayBuffer()) });
    }
  }

  return {
    blob: makeZip(files),
    name: `${base}-boardwright.zip`,
    files: files.map((f) => ({ name: f.name, size: f.data.length })),
  };
}

/* ── Downloads ────────────────────────────────────────────── */

export function download(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export const textBlob = (str, type = 'text/plain') => new Blob([str], { type: `${type};charset=utf-8` });
