// ── Build-prompt export ──────────────────────────────────────
// Generates the markdown that turns this session into a build order:
// recipe, stack with every ingredient's free tier + gotcha, cost
// expectations, known challenges, and constraints for the AI builder.

import { CATEGORIES } from './data-services.js';
import { RECIPES, FRONTENDS, TIERS } from './data-recipes.js';
import { state, activeCategories, currentPick, bundlerFor } from './state.js';
import { infraTotals, buildTokens, modelCosts, subscriptionPath } from './costmodel.js';
import { fmtUsd, fmtTokens } from './utils.js';

function stackLines() {
  const lines = [];
  for (const catKey of activeCategories()) {
    const cat = CATEGORIES[catKey];
    const pick = currentPick(catKey);
    if (!pick) {
      const b = bundlerFor(catKey);
      lines.push(`- **${cat.label}:** bundled with ${b ? b.name : 'another pick'} — no extra service or cost.`);
      continue;
    }
    if (pick.type === 'none') {
      lines.push(`- **${cat.label}:** skip — ${pick.gotcha}`);
      continue;
    }
    const bits = [`**${cat.label}:** ${pick.name}`];
    const meta = [];
    if (pick.free) meta.push(`free tier: ${pick.free}`);
    meta.push(`then ${pick.entry}`);
    if (pick.revshare) meta.push(`cut: ${pick.revshare}`);
    bits.push(`(${meta.join(' · ')})`);
    bits.push(`— watch out: ${pick.gotcha}`);
    lines.push('- ' + bits.join(' '));
  }
  return lines;
}

export function buildPrompt() {
  const recipe = RECIPES[state.recipe] || RECIPES.blank;
  const fe = FRONTENDS[state.frontend];
  const totals = infraTotals();
  const tokens = buildTokens();
  const models = modelCosts();
  const sub = subscriptionPath();
  const cheap = models[0];
  const quality = models.find(m => m.bestValue) || models[Math.floor(models.length / 2)];

  const tierRow = Object.keys(TIERS).map(k => `${TIERS[k].label} ${fmtUsd(totals[k])}/mo`).join(' · ');

  const lines = [
    `# Build a ${recipe.label} — stack + constraints (Doorman recipe)`,
    '',
    `> ${recipe.blurb}`,
    '',
    '## Frontend approach',
    '',
    `**${fe.label}** — ${fe.blurb}`,
    ...fe.pros.map(p => `- + ${p}`),
    ...fe.cons.map(c => `- − ${c}`),
    '',
    '## The stack (swaps already decided — do not relitigate)',
    '',
    ...stackLines(),
    '',
    '## Cost expectations',
    '',
    `- **Infra:** ${tierRow} (estimates — confirm on each pricing page; prices researched July 2026).`,
    `- **AI build:** ~${fmtTokens(tokens)} tokens total → ~${fmtUsd(cheap.usd)} on ${cheap.name} (budget) or ~${fmtUsd(quality.usd)} on ${quality.name} (quality).`,
    `- **Subscription path:** one month of ${sub.plan} (~$${sub.usd}/mo) likely covers it — ${sub.note}`,
    '',
    '## Known challenges (plan for these explicitly)',
    '',
    ...recipe.challenges.map((c, i) => `${i + 1}. **${c.title}** — ${c.note}`),
    '',
    '## Constraints for the build',
    '',
    '- Start inside free tiers; call out exactly which limit gets hit first and when.',
    '- If a bundled pick (BaaS) covers a category, use it — do not add a second service for the same job.',
    '- Ship the smallest working version of the core loop first, then the secondary screens.',
    '- Every secret goes in env vars; every third-party call degrades gracefully.',
    '- No analytics or tracking beyond the chosen analytics pick.',
    '',
    `_Generated by Doorman — doorman.neorgon.com_`,
  ];
  return lines.join('\n');
}
