// ── Ingest ───────────────────────────────────────────────────
// Four ways in, one shape out. Every path produces a releve/v1 document, so
// nothing downstream has to know where the numbers came from.
//
//   1. data/local.json: what `make mine` writes from your own transcripts.
//      Gitignored, so it exists on localhost and never in public.
//   2. data/demo.json: synthetic, shaped like a real 30-day scan. The
//      published default.
//   3. a dropped releve.json: someone else's scan, or your own from another
//      machine.
//   4. a dropped raw .jsonl: one transcript, aggregated and priced here in the
//      browser by the same engine (js/cost.js) the scripts use. This is the
//      cheapest way to check the page against a single session by hand.
//
// Nothing is uploaded on any path. 1 and 2 are fetches of files this site
// serves; 3 and 4 are the File API reading a local file.

import {
  Bucket, EXCLUDED, UNPRICED,
  addTokens, billableTotal, priceTurn, resolveModel, turnKey, uncachedCost, zeroTokens,
} from './cost.js';

const SCHEMA = 'releve/v1';

const DIMS = ['model', 'project', 'skill', 'effort', 'branch', 'lane', 'tier', 'version'];

/** Reject anything that is not the contract, by name, rather than rendering a
 *  half-empty page and letting the visitor guess why. */
export function validate(doc) {
  if (!doc || typeof doc !== 'object') throw new Error('not a JSON object');
  if (doc.schema !== SCHEMA) {
    throw new Error(`expected schema "${SCHEMA}", found ${JSON.stringify(doc.schema)}`);
  }
  for (const field of ['totals', 'days', 'dimensions']) {
    if (!doc[field]) throw new Error(`missing "${field}"`);
  }
  if (!doc.totals.cost) throw new Error('missing totals.cost');
  return doc;
}

/**
 * The page's default dataset. Prefers your own numbers when they are there.
 * data/local.json is gitignored, so on the published site this is always demo.
 * @returns {Promise<{doc: object, source: object}>}
 */
export async function loadDefault() {
  try {
    const res = await fetch('data/local.json', { cache: 'no-cache' });
    if (res.ok) {
      const doc = validate(await res.json());
      return {
        doc,
        source: {
          kind: 'local',
          label: 'your transcripts',
          note: `Real numbers from data/local.json, scanned ${(doc.generated || '').slice(0, 10)}. `
            + 'This file is gitignored and is never published.',
        },
      };
    }
  } catch { /* absent on the published site, which is the normal case */ }

  const res = await fetch('data/demo.json', { cache: 'no-cache' });
  if (!res.ok) throw new Error(`demo dataset: HTTP ${res.status}`);
  const doc = validate(await res.json());
  return {
    doc,
    source: {
      kind: 'demo',
      label: 'synthetic demo',
      note: doc.synthetic_note || 'Invented data, shaped like a real scan.',
    },
  };
}

/** Read a dropped or chosen file. Dispatches on extension, then on content. */
export async function fromFile(file, rates) {
  const text = await file.text();
  const isJsonl = /\.jsonl$/i.test(file.name) || (text.trimStart().startsWith('{') && text.includes('\n{'));

  if (!isJsonl) {
    const doc = validate(JSON.parse(text));
    return {
      doc,
      source: {
        kind: 'file',
        label: file.name,
        note: doc.anonymized
          ? `Loaded from ${file.name}, anonymized at scan time (${(doc.withheld || []).join(', ') || 'labels withheld'}).`
          : `Loaded from ${file.name}, generated by ${doc.generator || 'an unknown tool'}.`,
      },
    };
  }

  const doc = priceTranscript(text, rates, file.name);
  return {
    doc,
    source: {
      kind: 'jsonl',
      label: file.name,
      note: `Priced in this browser from ${file.name}: `
        + `${doc.totals.turns.toLocaleString()} turns across ${doc.totals.sessions} session(s). `
        + 'One transcript is not a window, so treat it as a spot check on the engine.',
    },
  };
}

// ── Raw transcript path ──────────────────────────────────────

/** A cwd is an absolute path on someone else's machine. The browser cannot know
 *  their home directory, so strip the common shapes and keep the rest, which is
 *  the part that distinguishes two projects with the same basename. */
function projectLabel(cwd) {
  if (!cwd) return '(unknown)';
  const stripped = String(cwd).replace(/^\/(?:Users|home)\/[^/]+\/?/, '');
  return stripped || String(cwd);
}

function percentile(values, p) {
  if (!values.length) return null;
  const sorted = [...values].sort((a, b) => a - b);
  const idx = (p / 100) * (sorted.length - 1);
  const lo = Math.floor(idx), hi = Math.ceil(idx);
  if (lo === hi) return sorted[lo];
  return Math.round(sorted[lo] + (sorted[hi] - sorted[lo]) * (idx - lo));
}

/**
 * Aggregate and price one raw transcript into a releve/v1 document.
 * The same three disciplines the scanner applies: per-turn model resolution,
 * per-turn date, and one count per response id keeping the richest copy.
 */
export function priceTranscript(text, rates, name = 'transcript') {
  const lines = text.split('\n');

  // Pass 1: the richest billable copy of each response id. One response is
  // written one entry per content block with the usage repeated on each, and a
  // resumed session replays its history on top of that; a later copy is
  // sometimes the fuller record. See turnKey().
  const best = new Map();
  const entries = [];
  for (const line of lines) {
    if (!line.trim()) continue;
    let entry;
    try { entry = JSON.parse(line); } catch { continue; }
    if (!entry || entry.type !== 'assistant') continue;
    const message = entry.message;
    if (!message || typeof message.usage !== 'object' || !message.usage) continue;
    entries.push(entry);
    const uid = turnKey(entry);
    if (!uid) continue;
    const weight = billableTotal(priceTurn(message, rates, (entry.timestamp || '').slice(0, 10)).tokens);
    if (!best.has(uid) || weight > best.get(uid)) best.set(uid, weight);
  }

  const totals = new Bucket();
  const dims = {};
  for (const d of DIMS) dims[d] = new Map();
  const dimRates = {};
  for (const d of DIMS) dimRates[d] = new Map();
  const days = new Map();
  const dayTot = new Map();
  const dayDims = new Map();
  const sessions = new Map();
  const rateKeys = {};
  const calib = new Map();
  const seen = new Set();

  let excludedTurns = 0;
  const excludedModels = new Map();
  let unpricedTurns = 0;
  const unpricedModels = new Map();
  const unpricedTokens = zeroTokens();
  let duplicateTurns = 0;
  // Response ids whose first copy in the file was not the richest one, so the
  // readout can report the same count the scanner does instead of a flat zero.
  const poorerFirst = new Set();
  let estimatedSplit = 0, tierAssumed = 0, iterationTurns = 0, multiIteration = 0;
  let firstDate = null, lastDate = null;

  for (const entry of entries) {
    const uid = turnKey(entry);
    if (uid) {
      if (seen.has(uid)) { duplicateTurns += 1; continue; }
      const message0 = entry.message;
      const weight = billableTotal(priceTurn(message0, rates, (entry.timestamp || '').slice(0, 10)).tokens);
      if (weight < best.get(uid)) {
        duplicateTurns += 1;
        poorerFirst.add(uid);
        continue;
      }
      seen.add(uid);
    }

    const message = entry.message;
    const usage = message.usage;
    const date = (entry.timestamp || '').slice(0, 10) || null;
    const priced = priceTurn(message, rates, date);

    if (priced.status === EXCLUDED) {
      excludedTurns += 1;
      const key = priced.canonical || '?';
      excludedModels.set(key, (excludedModels.get(key) || 0) + 1);
      continue;
    }

    if (date) {
      if (!firstDate || date < firstDate) firstDate = date;
      if (!lastDate || date > lastDate) lastDate = date;
    }
    if (priced.estimated_cache_split) estimatedSplit += 1;
    if (priced.tier_assumed) tierAssumed += 1;
    if (priced.from_iterations) {
      iterationTurns += 1;
      if ((usage.iterations || []).length > 1) multiIteration += 1;
    }

    const unpriced = priced.status === UNPRICED;
    let uncached = 0;
    if (unpriced) {
      unpricedTurns += 1;
      const key = priced.canonical || '(no model)';
      unpricedModels.set(key, (unpricedModels.get(key) || 0) + 1);
      addTokens(unpricedTokens, priced.tokens);
    } else {
      const { entry: rateEntry } = resolveModel(message.model, rates);
      uncached = uncachedCost(priced.tokens, rateEntry, rates, date, usage.speed, usage.service_tier);
    }
    totals.add(priced, uncached);

    const lane = entry.isSidechain ? 'subagent' : 'main';
    const values = {
      model: priced.canonical || '(no model)',
      project: projectLabel(entry.cwd),
      skill: entry.attributionSkill || '(none)',
      effort: entry.effort || '(unset)',
      branch: entry.gitBranch || '(none)',
      lane,
      tier: priced.tier || '(unset)',
      version: entry.version || '(unknown)',
    };

    const speed = usage.speed || 'standard';
    const tierName = priced.tier || 'standard';
    let rateKey = values.model;
    if (speed !== 'standard') rateKey += `#${speed}`;
    if (tierName !== 'standard') rateKey += `@${tierName}`;
    if (!rateKeys[rateKey]) {
      rateKeys[rateKey] = { model: values.model, speed, tier: tierName, status: priced.status };
    }

    for (const [dim, value] of Object.entries(values)) {
      const bucket = dims[dim].get(value) || dims[dim].set(value, new Bucket(value)).get(value);
      bucket.add(priced, uncached);
      const byRate = dimRates[dim].get(value) || dimRates[dim].set(value, {}).get(value);
      byRate[rateKey] = addTokens(byRate[rateKey] || zeroTokens(), priced.tokens);
    }

    if (date) {
      if (!days.has(date)) { days.set(date, new Map()); dayTot.set(date, new Bucket()); dayDims.set(date, {}); }
      const byModel = days.get(date);
      const mb = byModel.get(values.model) || byModel.set(values.model, new Bucket()).get(values.model);
      mb.add(priced, uncached);
      dayTot.get(date).add(priced, uncached);
      const slot = dayDims.get(date);
      for (const [dim, value] of Object.entries(values)) {
        if (dim === 'model') continue;
        slot[dim] = slot[dim] || {};
        const cell = slot[dim][value] || (slot[dim][value] = [0, 0, 0]);
        cell[0] += 1;
        cell[1] += priced.cost.total;
        cell[2] += unpriced ? 1 : 0;
      }
    }

    const sid = entry.sessionId || entry.session_id;
    if (sid) {
      let sess = sessions.get(sid);
      if (!sess) {
        sess = {
          id: sid, project: values.project, lane, started: entry.timestamp, ended: entry.timestamp,
          turns: 0, cost: 0, uncached_cost: 0, models: new Set(), unpriced_turns: 0,
        };
        sessions.set(sid, sess);
      }
      sess.turns += 1;
      sess.cost += priced.cost.total;
      sess.uncached_cost += uncached;
      sess.models.add(values.model);
      if (unpriced) sess.unpriced_turns += 1;
      const ts = entry.timestamp;
      if (ts) {
        if (!sess.started || ts < sess.started) sess.started = ts;
        if (!sess.ended || ts > sess.ended) sess.ended = ts;
      }
    }

    if (!unpriced) {
      const key = `${values.model}\u0000${values.effort}`;
      const sample = calib.get(key)
        || calib.set(key, { input: [], output: [], read: [], write: [] }).get(key);
      sample.input.push(priced.tokens.input);
      sample.output.push(priced.tokens.output);
      sample.read.push(priced.tokens.cache_read);
      sample.write.push(priced.tokens.cache_write_5m + priced.tokens.cache_write_1h);
    }
  }

  // ── Shape it like the scanner's output ──
  const dimOut = {};
  for (const dim of DIMS) {
    dimOut[dim] = [...dims[dim].entries()]
      .map(([key, bucket]) => ({
        key,
        turns: bucket.turns,
        unpriced_turns: bucket.unpriced_turns,
        tokens: { ...bucket.tokens },
        cost: { ...bucket.cost },
        uncached_cost: bucket.uncached,
        by_rate: dimRates[dim].get(key) || {},
      }))
      .sort((a, b) => b.cost.total - a.cost.total);
  }

  const daysOut = [...days.keys()].sort().map((date) => {
    const tot = dayTot.get(date);
    const byModel = {};
    for (const [model, bucket] of [...days.get(date).entries()].sort()) {
      byModel[model] = {
        turns: bucket.turns, unpriced_turns: bucket.unpriced_turns,
        tokens: { ...bucket.tokens }, cost: { ...bucket.cost },
        uncached_cost: bucket.uncached,
      };
    }
    return {
      date,
      turns: tot.turns,
      unpriced_turns: tot.unpriced_turns,
      tokens: { ...tot.tokens },
      cost: { ...tot.cost },
      uncached_cost: tot.uncached,
      by_model: byModel,
      dims: dayDims.get(date),
    };
  });

  const calibration = {};
  for (const [key, sample] of calib) {
    const [model, effort] = key.split('\u0000');
    calibration[model] = calibration[model] || {};
    calibration[model][effort] = {
      turns: sample.input.length,
      input_p50: percentile(sample.input, 50),
      output_p50: percentile(sample.output, 50),
      cache_read_p50: percentile(sample.read, 50),
      cache_write_p50: percentile(sample.write, 50),
      output_p90: percentile(sample.output, 90),
    };
  }

  const turnCounts = [...sessions.values()].map((s) => s.turns);
  const cachedIn = totals.tokens.cache_read;
  const totalIn = cachedIn + totals.tokens.input
    + totals.tokens.cache_write_5m + totals.tokens.cache_write_1h;

  return {
    schema: SCHEMA,
    generated: new Date().toISOString().replace(/\.\d+Z$/, 'Z'),
    generator: `js/ingest.js in the browser, from ${name}`,
    anonymized: false,
    withheld: [],
    rates: { version: rates.version, verified: rates.verified, source: rates.source },
    window: { from: firstDate, to: lastDate, days: null, requested_from: null, requested_until: null },
    plan: { monthly_cost: null, note: 'Set in the projector, not derived from tokens.' },
    totals: {
      sessions: sessions.size,
      turns: totals.turns,
      files: 1,
      tokens: { ...totals.tokens },
      cost: { ...totals.cost },
      counterfactual: {
        no_cache_total: totals.uncached,
        cache_saved: totals.uncached - totals.cost.total,
        note: 'Every cache read and cache write repriced as fresh input at the same model and rate.',
      },
      unpriced: {
        turns: unpricedTurns,
        models: [...unpricedModels.entries()].sort((a, b) => b[1] - a[1])
          .map(([model, turns]) => ({ model, turns })),
        tokens: unpricedTokens,
        note: 'No rate published in the rate card. Counted, never priced, never zeroed.',
      },
      excluded: {
        turns: excludedTurns,
        models: [...excludedModels.entries()].sort((a, b) => b[1] - a[1])
          .map(([model, turns]) => ({ model, turns })),
        note: 'Generated locally without an API call. Never billed.',
      },
      quality: {
        estimated_cache_split_turns: estimatedSplit,
        tier_assumed_turns: tierAssumed,
        iteration_turns: iterationTurns,
        multi_iteration_turns: multiIteration,
        duplicate_turns_skipped: duplicateTurns,
        richer_duplicates_preferred: poorerFirst.size,
        malformed_lines: 0,
        files_unreadable: 0,
      },
    },
    days: daysOut,
    dimensions: dimOut,
    rate_keys: rateKeys,
    sessions: [...sessions.values()]
      .sort((a, b) => b.cost - a.cost)
      .map((s) => ({ ...s, models: [...s.models].sort() })),
    calibration: {
      tokens_per_turn: calibration,
      turns_per_session: {
        p50: percentile(turnCounts, 50),
        p90: percentile(turnCounts, 90),
        mean: turnCounts.length
          ? Math.round((turnCounts.reduce((a, b) => a + b, 0) / turnCounts.length) * 100) / 100
          : null,
      },
      cache_hit_ratio: totalIn ? cachedIn / totalIn : null,
    },
  };
}
