// ── UI strings ───────────────────────────────────────────────
// Every word the interface shows lives here, keyed, so a second language is
// a second table and not a rewrite (the user's fork 3). There are two tables
// now, `en` and `es`, and `es` mirrors every key `en` has: a key present in one
// and missing in the other renders the literal [some.key] on the page, which
// tests/content.test.mjs is there to catch.
//
// Card faces carry no text at all, so nothing in here touches them. Rulebook
// prose comes from RULES.md (English) and RULES.es.md (Spanish), not from here.
//
// CARD NAMES. data/cards.json is the single source of truth for a card's
// English name, so `en` deliberately carries NO name table: cardName() falls
// through to card.name and cannot drift from the data. `es` carries the
// overlay, cards.name.<card id>, because the names are spoken out loud and a
// Spanish table needs Spanish names to shout.

export const STRINGS = {
  en: {
    nav: { learn: 'Learn', cards: 'Cards', play: 'Play', about: 'About', balance: 'Balance' },
    about: {
      title: 'About',
      lead: 'Who it was made for, what got cut, and who drew the pictures on the cards.',

      // Short labels for the vertical spine beside each section. The section's
      // real heading is a sentence and stays a sentence in the body; a spine
      // wants a word, and a sentence stood on its edge stretched the panel to
      // its own length and left a column of empty paper beside three lines of prose.
      spine: { origin: 'Origin', second: 'Second', table: 'Table', spells: 'Spells', art: 'Art', licence: 'Licence' },
      originTitle: 'It was made for my niece',
      origin1: 'She likes bricks, and I am usually the one on the floor with her. The rules we invented changed every few minutes and nobody could lose. So I wrote some down.',
      origin2: 'She also wanted the dice. All of them, not just the six-sided one. So every die from d4 to d20 has to work, and the game turns on a roll instead of a number.',
      origin3: 'What I was after: the smallest set of rules that still lets her lose.',

      secondTitle: 'This is the second version',
      second1: 'The first one had too many rules. We played it, and the parts she liked were not the ones I had written the most rules for. The rest came out.',
      second2: 'It is short because it was played, not because it was rushed.',

      tableTitle: 'There is no board',
      table1: 'The boss is built from bricks, the hero is a figure from the same box, and the cards do the arithmetic.',
      table2: 'No card names a toy. The bricks are yours, whichever you own.',

      spellsTitle: 'The spells that were cut',
      spells1: 'An early version let the player invent spells. You wrote one, named it, used it. Too much to hold up, so it went.',
      spells2: 'In its place is the oldest tabletop move: hand it back rather than write another rule. The card never says its name. You do.',
      spells3: 'Run says you got away and the boss says how well. Where you ran and what you hid behind, the rules never ask.',

      artTitle: 'The art',
      artLead: 'Most of the card art is from The Noun Project, under CC BY. Attribution is a condition of that licence, not a courtesy. The files are modified: credit moved here, viewBox cropped, colour at render time. The table below is built from data/art-manifest.json, so it cannot drift from the cards.',
      artInHouse: 'The rest I drew myself, on a 24 by 24 stroked grid. The boss size cards keep those glyphs on purpose: one figure that grows across five cards tells you which boss is bigger.',
      artLoading: 'Reading the art manifest',
      artFail: 'data/art-manifest.json did not load. Serve the folder over HTTP (make serve) and reload.',
      statCredited: 'icons credited',
      statCreators: 'creators',
      statInHouse: 'slots drawn in house',
      creditsNote: 'The same list ships as CREDITS.md and goes with the folder.',
      cols: { icon: 'Icon', use: 'Used for', creator: 'Creator', licence: 'Licence', what: 'What' },

      licenceTitle: 'Licence',
      licenceLead: 'The code is mine to give away. The art is not.',
      licence: {
        codeWhat: 'Rules, card data, tools, site code and all the text',
        codeIs: 'MIT',
        artWhat: 'The icons in art/',
        artIs: 'CC BY, per the table above',
        glyphsWhat: 'The glyphs drawn in house',
        glyphsIs: 'MIT, original',
      },
      licenceNote: 'The artists let anyone use these pictures on one condition: their names go wherever the pictures go. Copy this folder and you take that on.',
    },
    footer: { version: 'v0.1.0' },
    // The page chrome that lives in index.html rather than in a view: the
    // header subtitle, the skip link, the two landmark labels and the footer
    // note. js/events.js writes these onto the elements carrying data-i18n /
    // data-i18n-label, because render.js only ever owns what is inside
    // #viewRoot and none of this is.
    chrome: {
      subtitle: 'Balance your attack and your defense',
      skip: 'Skip to content',
      sections: 'Sections',
      closeDialog: 'Close dialog',
      footerNote: 'Rules and cards are MIT. Card art is CC BY, credited on the About page. Runs save on this device only.',
    },
    common: {
      loading: 'Loading the cards',
      loadFail: 'The card data did not load. Serve the folder over HTTP (make serve) and reload.',
      close: 'Close',
      print: 'Print',
      copied: 'Copied',
      placeholder: 'placeholder art',
      sayIt: 'Say it out loud',
    },
    cards: {
      title: 'The cards',
      lead: 'A hundred and eleven cards, poker size, with no word printed on any of them. The corners carry the numbers. The picture is the name, and saying it out loud is your job. Tap a card for what it does.',
      // What each card DOES, one line, for the inspector and the detail modal.
      // Numbers restate data/cards.json; rules restate RULES.md. Drafted against
      // both and spot-checked: a number here that drifts from the data is a bug.
      effect: {
        strike: 'One action, no bet: deal 25. It always lands.',
        focus: 'Bet 1 life card and roll Sure: 75 damage. The card is Spent whether it lands or not.',
        'all-in': 'Two actions. Bet any Ready cards and roll Even: 100 damage for each card bet, or nothing at all.',
        bubble: 'One action, no card: absorb the next 25 the boss deals you this round. It still works under Rage.',
        run: 'One action: you Hide until the boss acts. Its Strike misses you entirely; anything else hits for half.',
        invention: 'Say your spell out loud, bet 1 card and roll Wild: it lands for 350, the biggest number in your deck.',
        slash: 'Bet 1 card and roll Sure: 75 damage. No colour of its own, so it attacks with your element.',
        ember: 'Bet 1 card and roll Sure: 75 damage as Fire, whoever plays it.',
        torrent: 'Bet 1 card and roll Sure: 75 damage as Water, whoever plays it.',
        tremor: 'Bet 1 card and roll Sure: 75 damage as Earth, whoever plays it.',
        gale: 'Bet 1 card and roll Sure: 75 damage as Wind, whoever plays it.',
        piercer: 'Bet 1 card and roll Sure: 100 damage, attacking with your element.',
        firebolt: 'Bet 1 card and roll Sure: 100 damage as Fire.',
        'ice-spear': 'Mage only. Bet 1 card and roll Sure: 100 damage as Water.',
        boulder: 'Bet 1 card and roll Sure: 100 damage as Earth.',
        cyclone: 'Bet 1 card and roll Sure: 100 damage as Wind.',
        'slash-wave': 'Knight only. Bet 2 cards and roll Sure: 225 damage, attacking with your element.',
        nova: 'Bet 2 cards and roll Sure: 225 damage as Fire.',
        'cold-curse': 'Bet 2 cards and roll Sure: 225 damage as Water.',
        earthquake: 'Bet 2 cards and roll Sure: 225 damage as Earth.',
        tempest: 'Bet 2 cards and roll Sure: 225 damage as Wind.',
        'soul-strike': 'Hunter only. Bet 2 cards and roll Even: 400 damage, attacking with your element.',
        pyre: 'Bet 2 cards and roll Even: 400 damage as Fire.',
        maelstrom: 'Bet 2 cards and roll Even: 400 damage as Water.',
        landslide: 'Bet 2 cards and roll Even: 400 damage as Earth.',
        thunderhead: 'Bet 2 cards and roll Even: 400 damage as Wind.',
        meteor: 'Bet 3 cards and roll Even: 750 damage as Fire.',
        deluge: 'Bet 3 cards and roll Even: 750 damage as Water.',
        cataclysm: 'Bet 3 cards and roll Even: 750 damage as Earth.',
        hurricane: 'Bet 3 cards and roll Even: 750 damage as Wind.',
        reaper: 'Necromancer only. Bet 3 cards and roll Even: 750 damage, attacking with your element.',
        taunt: 'Knight only. One action, no bet: the boss rolls its die now, face up, and you finish your turn knowing.',
        knight: 'Once per round, guard 25 damage with no card at all. It is a guard, so Rage goes straight through it.',
        mage: 'Your Focus deals +25: 100 instead of 75.',
        hunter: 'Once per round, reroll one failed check.',
        necromancer: 'When a minion falls, take one of its life cards as your own, Ready. In your hands it guards 25.',
        cure: 'Return 2 of your Broken life cards to Ready.',
        barrier: 'Cancel one boss action entirely: whatever it rolled simply does not happen.',
        ally: 'A companion figure: it deals the boss 25 free each turn and draws its Strike away from you. 50 defense.',
        rune: 'One check this level succeeds automatically. Declare it before you roll.',
        relic: 'Every attack you land this level deals +25.',
        chest: 'Draw 2 more Advantage cards.',
        'boss-s': 'The Minion: size S, 2 boss cards of 100, deals you 25 each round. It only arrives as a Summon, never alone.',
        'boss-m': 'Size M: 4 cards of 100, Damage 50, Rage from round 4. On a 1 it Skitters: no damage, and your next landed attack deals +25.',
        'boss-l': 'Size L: 7 cards of 100, Damage 50, Rage from round 4. On a 4 it Coils: a Summon whose new minion strikes at once.',
        'boss-l2': 'Size L: 10 cards of 100, Damage 75, Rage from round 4. On a 1 it holds Bedrock: a Brace, and it repairs 25.',
        'boss-xl': 'Size XL: 12 cards of 100, Damage 100, Rage from round 4. On a 6, Stormbreak: Ruin, and again if none of your cards stands.',
        'boss-um': 'Size UM: 20 cards of 100, Damage 100, Rage from round 5. On a 5 it Hoards: it steals 1 standing life card instead of dealing damage.',
        volcano: 'A Fire place: every Fire attack that lands here deals +25.',
        river: 'A Water place: every Water attack that lands here deals +25.',
        mountain: 'An Earth place: every Earth attack that lands here deals +25.',
        desert: 'A Wind place: every Wind attack that lands here deals +25.',
        forest: 'Once a level, Hiding costs nothing: no card, no action. There is cover everywhere.',
        village: 'You start the level with 1 extra Ready life card.',
        castle: 'The boss acts twice on round 1, and your Spent cards Recover between the two swings.',
        'life-fire': 'A Fire life card. Bet it to attack; guard with it Ready and it returns next round; guard Spent and it Breaks.',
        'life-water': 'A Water life card. Bet it to attack; guard with it Ready and it returns next round; guard Spent and it Breaks.',
        'life-earth': 'An Earth life card. Bet it to attack; guard with it Ready and it returns next round; guard Spent and it Breaks.',
        'life-wind': 'A Wind life card. Bet it to attack; guard with it Ready and it returns next round; guard Spent and it Breaks.',
        'life-extra': 'A white life card, earned after each level you win. No element; it bets and guards 25 like any other.',
        'life-boss': 'One card of the boss wall, worth 100. Deal 100 and turn one over: the shrinking pile is its health bar.',
        'second-wind': 'Optional. When you would go Down, come back instead. Free once a level, then the roll climbs and the rescue thins: 4 cards back, then 3, then 2, then 1.',
        sidekick: 'A second player owns Strike and Run: those actions are theirs to choose, say and roll. The life pool stays shared.',
        grudge: 'When a boss defeats you, slide this under its card: next fight, one check you choose succeeds automatically.',
        'aid-checks': 'A reference: the four check steps and the target number for every die, so the die you own can play.',
        'aid-turn': 'A reference: the round in order. Recover, take your 3 actions, minions strike, the boss acts.',
        'aid-boss': 'A reference: the d6 the boss rolls each round. 1 Brace, 2-3 Strike, 4 Summon, 5 Roar, 6 Ruin.',
        'aid-breaks': 'Say what part you went for and take it off: a Wound (50 gone), a Cripple (25 off everything it deals) or a Trophy (one free check). Two per boss, and the grown-up sets how hard it is to do.',
      'aid-track': 'A counter, not a rule: track the damage dealt in steps of 25, with a die counting the hundreds.',
      },
      printBtn: 'Print',
      sheets: 'sheets',
      scopeLabel: 'What to print',
      scope: { all: 'Everything', essentials: 'Essentials', first: 'First Game' },
      scopeHint: {
        all: 'The whole box.',
        essentials: 'Skips the 7 biome cards: anything on the table can be the place. Life and mode cards stay.',
        first: 'Everything the First Game deals: one boss, six cards, all four elements of life, the aids.',
      },
      printDeck: 'Print this deck',
      printing: 'Filling the print sheet',
      paper: 'Paper',
      a4: 'A4',
      letter: 'Letter',
      backs: { _: 'Card backs', none: 'no backs', few: '4 backs', all: 'a back per card' },
      filterAll: 'All decks',
      copies: 'copies',
      deck: { attack: 'Attack', skill: 'Skills', class: 'Classes', advantage: 'Advantage', boss: 'Bosses', biome: 'Biomes', life: 'Life', mode: 'Gentle mode', aid: 'Player aids' },
      val: { betAny: 'any number of Ready cards', none: 'none', lifeCard: 'life card', lifeCards: 'life cards', xBet: '4 × what you bet', classOnly: 'only' },
      corner: { bet: 'Bet', check: 'Check', tier: 'Tier', damage: 'Damage', actions: 'Actions', element: 'Element', class: 'Class', effect: 'Effect', passive: 'Passive', size: 'Size', life: 'Life cards', rage: 'Rage from round', rule: 'Rule', value: 'Worth', copies: 'Copies', icon: 'Glyph' },
      check: { none: 'always lands', sure: 'Sure, 75%', even: 'Even, 50%', hard: 'Hard, 25%', wild: 'Wild, 15%' },
      // The bare name of a step, with no odds attached. The views used to
      // capitalise the raw id ('sure' -> 'Sure'), which is a name only in
      // English; the ladder needs its own words in every language.
      step: { sure: 'Sure', even: 'Even', hard: 'Hard', wild: 'Wild' },
      sort: { _: 'Sort by', deck: 'Deck', element: 'Element', tier: 'Tier', class: 'Class', check: 'Risk', damage: 'Damage', name: 'Name' },
      // The four elements are spoken out loud like a card name, so they are named
      // here rather than capitalised off their English id at seven render sites.
      element: { _: 'Element', all: 'Any element', none: 'Yours', fire: 'Fire', water: 'Water', earth: 'Earth', wind: 'Wind' },
      tier: { _: 'Tier', all: 'Any tier' },
      klass: { _: 'Class', all: 'Any class', none: 'Open to all' },
      showBacks: 'Show backs',
      showFaces: 'Show faces',
      reset: 'Clear filters',
      empty: 'No card matches those filters.',
      face: 'Face',
      back: 'Back',
      dlFace: 'Download the face',
      dlBack: 'Download the back',
      dlFailed: 'That card did not export. Reload and try again.',
      printOrder: 'Printing always uses the boxed order, whatever this list is sorted by.',
    },
    learn: {
      heroKicker: 'A print-and-play boss rush for one player',
      heroTitle: 'Balance your <em>attack</em> and your <em>defense</em>.',
      heroLead: 'Build the boss out of bricks. Play your hero as a figure. The cards in front of you are your attack and your defense at once: betting is free until the boss swings and you have nothing left standing. One die, a hundred and eleven cards, and the toys already on the table.',
      ctaPlay: 'Play on screen',
      ctaCards: 'Print the cards',
      ctaFirst: 'First Game: one boss, six cards',
      walkthroughKicker: 'How it plays',
      rulebookTitle: 'The rulebook',
      rulebookLead: 'The complete rules, the same text that ships with the cards. About ten minutes to read.',
      // The rulebook file the deck fetches, per language. It is a string in the
      // table rather than a branch in the view so a third language is a third
      // row here and no code change at all.
      rulebookFile: 'RULES.md',
      rulebookFail: 'RULES.md did not load. It ships in the repo next to this page.',
      // A citation, spelled the way a person says it out loud: "Rule 5", not
      // "rules s5". The section symbol is a typesetting mark from legal writing
      // and it means nothing to a child reading a card game. The section NUMBERS
      // are the same in both rulebooks; only the word in front of them changes.
      rulesRef: 'Rule ',
      bridgeTitle: 'Any die you own',
      bridgeLead: 'Find your row. Roll. Meet or beat the number. Three d6 track a d20 within 1.2 points at every step.',
      fidelityLead: "Worst gap between a step's stated odds and the die's real odds:",
      fidelityUnit: 'points.',
      step: 'Step',
      odds: 'Odds',
      prev: 'Back',
      next: 'Next',
      slideOf: 'of',
      contents: 'Contents',
      deckHint: 'Arrow keys, or swipe.',
      slide: { dice: 'Any die you own', rulebook: 'The rulebook', playNow: 'Try it right now' },
      playNowKicker: 'No printer needed',
      playNowTitle: 'Try it right now',
      playNowLead: 'The Play tab runs the whole game on this screen: the same cards, a stand-in hero, and a boss drawn as if someone had built it. Setup is four quick choices. When you want the real table, print the cards and build the boss yourself.',
      playNowCta: 'Play the First Game',
      playNowDesktop: 'Made for a desktop screen. On a phone it works for a quick try.',
      ctaPlayNow: 'Try it on screen now',
    },
    play: {
      title: 'Play',
      setupTitle: 'Set up your run',
      // The three ways in. Each says how LONG it is and who it is for, because
      // that is the question being asked, and the two cards that used to sit
      // here were the same shape in the same colour and read as one choice.
      quickRun: 'Quick run',
      quickRunLead: 'Three bosses: the first, the middle and the last. They are scaled down so three levels tell the whole story, and you get a real ending in one sitting.',
      kindWho: { first: 'Your first time, or a new player at the table', quick: 'You want to reach the last boss today', full: 'A run you leave set up and come back to' },
      kindLevels: { first: 'one level', quick: 'three levels', full: 'five levels' },
      kindMinutes: { first: '15 min', quick: '45 min', full: '2 h+' },
      firstGame: 'First Game',
      firstGameLead: 'Level 1 only, with Strike, Focus, All In, Bubble, Run and Invention. No classes, no skills, no Advantage. The whole game is already in those six cards.',
      fullRun: 'Full run',
      fullRunLead: 'Five bosses. Classes after the first, a new skill after every level, Advantage cards along the way.',
      element: 'Your element',
      die: 'Your die',
      mode: 'Mode',
      story: 'Story', standard: 'Standard', nightmare: 'Nightmare',
      modeHint: { story: 'one rung easier, for a first run or a younger player', standard: 'the table as printed', nightmare: 'one rung harder' },
      start: 'Start',
      resume: 'Resume run',
      abandon: 'Abandon run',
      level: 'Level',
      round: 'Round',
      boss: 'Boss',
      // The screen-reader label on the boss's health bar, read as
      // "Boss life: 300 / 400". Its neighbour bossPile names the physical pile.
      bossLife: 'Boss life',
      hero: 'You',
      minion: 'Minion',
      ready: 'Ready', spent: 'Spent', broken: 'Broken',
      actionsLeft: 'actions left',
      target: 'Target',
      body: 'the boss',
      bet: 'Bet',
      betHint: 'Pick how many Ready cards to stake.',
      needActions: 'needs 2 actions and your turn has fewer left',
      needBet: 'needs a Ready life card to bet',
      roll: 'Roll',
      typeRoll: 'or type your roll',
      need: 'need',
      hit: 'Hit!', miss: 'Miss',
      endTurn: 'End turn',
      skipTurn: 'Skip turn',
      resolveAll: 'Resolve the rest',
      resolveAllHint: 'Roll every remaining check at once. The log keeps each roll.',
      throw: 'Throw',
      damage: 'damage',
      lands: 'lands',
      bracedHalved: 'Braced: halved',
      rm: {
        lead: 'The plan is set. This turn holds',
        check: 'roll to make',
        checks: 'rolls to make',
        noChecks: 'Everything lands on its own: no rolls needed.',
        throw: 'Throw the dice',
        fast: 'Resolve it all at once',
        back: 'Back to the plan',
        close: 'Done',
        next: 'Next',
        step: 'Step',
        of: 'of',
        throwHint: 'One die at a time. You throw, you see it land, you see what it did.',
        fastHint: 'Every roll at once. The ledger keeps each one.',
      },
      // Break points (RULES.md section 7). The game never names the part: the
      // player says what came off, so every string here talks about the break
      // and never about an eye, a wing or a tail.
      brk: {
        title: 'Break a part',
        say: 'Say what you went for, then pick what it buys.',
        wound: 'Wound',
        woundHint: 'It loses {n} on the spot.',
        cripple: 'Cripple',
        crippleHint: 'Everything it deals drops by {n} for the rest of the level.',
        trophy: 'Trophy',
        trophyHint: 'One check this level succeeds by itself.',
        left: 'parts left',
        none: 'No parts left on this one.',
        costs: 'costs an action',
        free: 'granted',
        held: 'The part holds.',
        broke: 'It comes off!',
        cancel: 'Not this time',
      },
      dm: {
        enable: 'Break points',
        enableHint: 'Say what part you went for and take it off: a Wound, a Cripple or a Trophy. Off by default, because the game is complete without it. Turn it on when your table wants to describe the fight, not just play it.',
        title: 'Who decides a break?',
        friendly: 'Friendly',
        friendlyHint: 'Say it and it happens. No roll, no cost. For the youngest table.',
        assisted: 'Assisted',
        assistedHint: 'A Hard check decides it. The middle setting, and the one to start on.',
        hardcore: 'Hardcore',
        hardcoreHint: 'A Wild check, and it costs one of your three actions.',
        cap: 'Parts per boss',
        capOff: 'Breaking parts is off',
        edit: 'Change the numbers',
        wound: 'A Wound tears off',
        cripple: 'A Cripple takes off',
      },
      levels5: '5 levels',
      levelCleared: 'cleared',
      outcome: { win: 'won', loss: 'lost' },
      braceWhat: 'no damage, and it halves what it takes next turn',
      summonWhat: 'of its life moves under a minion',
      absorbed: 'absorbed',
      oneAction: 'action', manyActions: 'actions', betAny: 'any',
      autoStep: 'auto',
      reorder: 'Drag to change the order',
      moveEarlier: 'Move earlier',
      moveLater: 'Move later',
      abandoned: 'Run abandoned',
      drew: 'Drew',
      castleAgain: 'Castle: the boss acts again',
      bossThrow: 'Throw the boss\u2019s die',
      bossThrown: 'The boss threw',
      bossOwnDie: 'or tap the face your own d6 showed',
      simpleMode: 'Keep the table simple',
      simpleModeHint: 'No biomes and no signature moves: the plain reaction table and nothing else. The way to learn the core game before the extras.',
      takeIt: 'Take it',
      go: 'Go',
      finish: 'Finish',
      outOfActions: 'Out of actions. End the turn and the boss acts.',
      bossAskHow: 'Rolled a real d6? Tap the face it shows. No die? The button rolls for you.',
      tour: {
        wall: 'The wall of cards is the boss\u2019s life. Every 100 damage knocks one card down; knock them all down and the level is yours.',
        life: 'These are your life cards. Bet them to power attacks, and while they stand they guard you when the boss hits back.',
        hand: 'Your hand. Tap cards to queue up to three actions; hover one (or press and hold) to see what it does.',
        go: 'Resolve rolls your checks. When your plan is done, End turn hands the die to the boss.',
        next: 'Next',
        skip: 'Skip the tour',
        done: 'Got it',
      },
      firstWon: 'You beat the First Game.',
      hist: { level: 'Level', result: 'Result', rounds: 'Rounds', broken: 'Broken' },
      bossTurn: 'Boss acts',
      bossRoll: 'The boss rolls',
      hide: 'Hide', move: 'Move',
      signatureName: { skitter: 'Skitter', coil: 'Coil', bedrock: 'Bedrock', stormbreak: 'Stormbreak', hoard: 'Hoard' },
      reactionName: { brace: 'Brace', strike: 'Strike', summon: 'Summon', roar: 'Roar', ruin: 'Ruin' },
      what: {
        strike: 'Always lands. 25 damage for one action and no cards.',
        focus: 'Bet one life card. 75 damage if the Sure roll lands, and the card is spent either way.',
        'all-in': 'Bet as many Ready cards as you like: 100 for each of them, on a coin flip. Costs two of your three actions.',
        bubble: 'Absorbs the next 25 you take this round. It is only worth an action under Rage: outside Rage a Ready card guards for free and comes back, so a Bubble buys you nothing.',
        invention: 'Say the spell out loud first: its name, its look, what it does to the room. Bet one card, roll the Wild check, and it lands for 350. The biggest number in your deck, behind the longest odds.',
        run: 'You are Hidden until the boss acts. Its Strike goes right past you for nothing; anything else still finds you, but only for half.',
      },
      hideHint: 'Free in the Forest: you are Hidden until the boss acts.',
      hidden: 'Hidden',
      rage: 'Rage. Double damage, no guard.',
      rageSoon: 'Rage next round.',
      won: 'The boss falls!',
      lost: 'You are Down.',
      runWon: 'You cleared all five levels.',
      nextLevel: 'Next level',
      newRun: 'New run',
      pickClass: 'Choose your class',
      draftTitle: 'Pick one skill',
      draftLead: 'Three revealed, keep one.',
      advDraw: 'You draw an Advantage card',
      advHand: 'Advantage',
      playAdv: 'Play',
      useRune: 'Use the Rune on this check',
      reroll: 'Hunter: reroll',
      knight: 'Knight guard used',
      barrierPrompt: 'Play Barrier to cancel this?',
      letItHappen: 'Let it happen',
      log: 'Log',
      logShow: 'Show the log', logHide: 'Hide the log',
      // The boss speaks above its own head instead of in the log
      // What the boss says when nothing is resolving. It used to be one sentence
      // forever, which is the line most often on the screen, so it was also the
      // clearest chance the board had to have a personality and did not take it.
      // The state lines are checked first and win; `idle` rotates by round.
      // The fight's story beats. `events` fire once on the render that earned
      // them (ui.event); `win`/`loss` take over the bubble at the end; `bossIdle`
      // gives each boss two lines of its own on top of the shared rotation.
      say: {
        hidden: 'It cannot see where you went.',
        allyNear: 'It keeps glancing at the small one beside you.',
        minions: 'The little ones circle you.',
        bossHurt: 'It is not standing straight any more.',
        heroHurt: 'It has noticed your hands are shaking.',
        braced: 'It has dug in and is waiting for you.',
        idle: [
          'The boss watches you.',
          'The boss has not moved. That is somehow worse.',
          'Something in the pile shifts, and settles.',
          'It is deciding which of you goes first.',
        ],
        events: {
          firstBlood: 'The first one landed. It felt that.',
          bigHit: 'The whole table shook. It is still ringing.',
          whiff: 'It watched that one sail past. It looks pleased.',
          revived: 'You got back up. It was not expecting that.',
        },
        win: [
          'It comes apart, one brick at a time.',
          'The wall is gone. So is the thing behind it.',
        ],
        loss: [
          'The table is quiet. Set your cards back up: it will wait.',
          'Down, not done. The rematch starts whenever you do.',
        ],
        bossIdle: {
          'boss-m': ['It clicks its shell at you.', 'Small, fast, and very sure of itself.'],
          'boss-l': ['It coils, slow as a tide.', 'It has drowned braver heroes than you.'],
          'boss-l2': ['Stone grinds against stone.', 'It has stood here longer than your house.'],
          'boss-xl': ['The air tastes of storm.', 'Its wings blot out the lamp.'],
          'boss-um': ['It counts its cards like coins.', 'Everything you break, it keeps.'],
        },
      },
      setup: {
        step1: 'How you will play',
        step2: 'Who you are',
        step3: 'Your die, and how kind the game is',
        step4: 'Set the table',
        next: 'Next',
        back: 'Back',
        again: 'Same table as last time',
        tableLead: 'The screen is the referee. The table is the game. Before you start:',
        tableSkip: 'Just trying it on screen? Nothing to build: press Start.',
        tableBoss: 'Build the boss out of bricks. Make it about as big as its wall of cards.',
        tableHero: 'Pick your hero figure and stand it facing the boss.',
        tableLife: 'Put your 4 life cards standing in front of you, and keep your die close.',
        keys: 'Arrow keys move between choices, Enter continues.',
      },
      bossAsk: 'What did the boss roll?',
      bossRollFor: 'Roll for the boss',
      abandonSure: 'Sure? Tap again to abandon',
      undoLast: 'Undo last',
      confirmKeep: 'Keep',
      pickFirst: 'Tap one to choose it',
      bossWatch: 'The boss watches you.',
      aimedAtYou: 'aimed at you',
      aimedAtAlly: 'aimed at your Ally',
      unguardable: 'unguardable',
      // The gear shelf: what you already have in play
      shelf: 'In play',
      relic: 'Relic', rune: 'Rune', bubbleSlot: 'Bubble',
      // The number is ALLY_DEF in game/engine.js, not a word in here: the
      // rulebook can change it and this string must not have to be found.
      ally: 'Ally', allyDef: 'defense',
      allyGone: 'The Ally is gone.',
      cover: 'Cover the Ally',
      coverHint: 'Take the hit yourself, whole, and the Ally stays.',
      slotEmpty: 'empty',
      // The three bands of the action panel
      bandCards: 'Your cards', bandGo: 'Resolve',
      pickHint: 'the die is waiting',
      placeholderNote: 'Enemies and heroes are placeholders drawn from bricks. The real art comes later.',
      // Second Wind, the gentle-mode card
      secondWind: 'Second Wind',
      secondWindHint: 'A safety net. The first comeback each level is free and stands you all the way up, then the roll climbs and the rescue thins: 4 cards back, then 3, then 2, then 1.',
      down: 'You are Down',
      downFree: 'Your first comeback this level is free.',
      downLadder: 'The comeback needs',
      reviveTry: 'Take the comeback',
      reviveGiveUp: 'Let the level end',
      // The plan lane
      plan: 'Your turn',
      planHint: 'Click a card once for each action you want it to take. Click a number to drop that step.',
      planEmpty: 'Pick a card. Three actions this turn.',
      resolvePlan: 'Resolve the turn',
      clearPlan: 'Clear',
      planStep: 'Step',
      reaction: 'Reaction',
      reactionHint: 'Barrier waits here for the boss to act.',
      attachTo: 'attached to step',
      tooManyActions: 'That is more than the actions left this turn.',
      notEnoughReady: 'By that step there is no Ready card left to bet.',
      keys: '1 to 9 pick a card · Enter resolves · Backspace undoes',
      // The rest of the table, shown but not played
      table: 'On the table',
      drawPile: 'Skills',
      advPile: 'Advantage',
      extraPile: 'Extra lives',
      biomeCard: 'Biome',
      bossPile: 'Boss life',
      faceDown: 'face down',
      inTheBox: 'in the box',
    },
    balance: {
      title: 'Balance',
      lead: 'The same engine the runner uses, played thousands of times by four stand-in styles. The published table in BALANCE.md comes from tools/sim.py at 20,000 fights per cell; this one is for trying things.',
      trials: 'Fights per cell',
      bonus: 'Affinity bonus',
      run: 'Run',
      running: 'Running',
      stop: 'Stop',
      style: { turtle: 'turtle', safe: 'safe', adaptive: 'adaptive', gamble: 'gamble' },
      fightsPerCell: 'fights per cell', runCompletion: 'Five-level run completion on the adaptive line', thisRun: 'This run', rulebookRules: 'rulebook rules', legacyRules: 'tools/sim.py legacy rules', bonus: 'bonus', publishedCaption: 'Published: docs/BALANCE.md, tools/sim.py, seed 7, no bonus, no classes, no Advantage', adaptiveCol: 'adaptive',
      cols: { level: 'Level', win: 'win', rounds: 'rounds', broken: 'broken' },
      legacy: 'Match tools/sim.py exactly',
      legacyHint: 'Reproduces three simplifications the Python simulator makes (Brace never halves, Summon moves a flat 100, Roar flattens the next check to Even) so its table can be checked. Off, the engine plays the rulebook.',
      advantage: 'Advantage deck',
      klass: 'Class',
      none: 'none',
    },
  },

  // ── Spanish ────────────────────────────────────────────────
  // Neutral Latin American Spanish, read out loud to a child: short sentences,
  // no vosotros, no peninsular vocabulary. Numbers, dice notation (d20, 2d6)
  // and percentages are left exactly as the English has them.
  //
  // The three life-card states are the heart of the game, so they are named for
  // the gesture the card makes on the table rather than for an abstraction:
  // En Pie (upright), De Lado (turned sideways), Rota (broken). Three different
  // lengths, three different stress patterns, no two of them confusable across
  // a table.
  es: {
    nav: { learn: 'Aprender', cards: 'Cartas', play: 'Jugar', about: 'Acerca de', balance: 'Balance' },
    about: {
      title: 'Acerca de',
      lead: 'Para quién se hizo, qué se cortó y quién dibujó las figuras de las cartas.',

      spine: { origin: 'Origen', second: 'Segunda', table: 'Mesa', spells: 'Hechizos', art: 'Arte', licence: 'Licencia' },
      originTitle: 'Lo hice para mi sobrina',
      origin1: 'Le gustan los bloques y casi siempre el que juega con ella en el suelo soy yo. Las reglas que inventábamos cambiaban cada cinco minutos y nadie podía perder. Así que escribí algunas.',
      origin2: 'También quería los dados. Todos, no solo el de seis. Así que cada dado, del d4 al d20, tiene que servir, y el juego gira sobre una tirada y no sobre un número.',
      origin3: 'Lo que buscaba: las reglas mínimas que todavía la dejen perder.',

      secondTitle: 'Esta es la segunda versión',
      second1: 'La primera tenía demasiadas reglas. La jugamos, y las partes que le gustaron no eran aquellas para las que yo había escrito más reglas. El resto se fue.',
      second2: 'Es corto porque se jugó, no porque se hiciera rápido.',

      tableTitle: 'No hay tablero',
      table1: 'El jefe se arma con bloques, el héroe es una figura de la misma caja, y las cartas hacen las cuentas.',
      table2: 'Ninguna carta nombra un juguete. Los bloques son tuyos, los que tengas.',

      spellsTitle: 'Los hechizos que se cortaron',
      spells1: 'Una versión temprana dejaba inventar hechizos. Escribías uno, le ponías nombre, lo usabas. Era demasiado complicado de sostener, así que se fue.',
      spells2: 'En su lugar quedó la jugada más vieja del rol de mesa: devolvérselo al jugador en vez de escribir otra regla. La carta nunca dice su nombre. Lo dices tú.',
      spells3: 'Escape dice que te escapaste y el jefe dice qué tan bien. Dónde corriste y detrás de qué te escondiste, las reglas nunca lo preguntan.',

      artTitle: 'El arte',
      artLead: 'Casi todo el arte viene de The Noun Project, bajo CC BY. La atribución es una condición de esa licencia, no una cortesía. Los archivos están modificados: el crédito se movió aquí, se recortó el viewBox, el color se aplica al dibujar. La tabla de abajo se arma con data/art-manifest.json y no puede alejarse de las cartas.',
      artInHouse: 'El resto lo dibujé yo, sobre una cuadrícula trazada de 24 por 24. Las cartas de tamaño del jefe siguen con esos glifos a propósito: una figura que crece a lo largo de cinco cartas te dice cuál jefe es más grande.',
      artLoading: 'Leyendo el manifiesto de arte',
      artFail: 'data/art-manifest.json no cargó. Sirve la carpeta por HTTP (make serve) y recarga.',
      statCredited: 'íconos acreditados',
      statCreators: 'autores',
      statInHouse: 'espacios dibujados en casa',
      creditsNote: 'La misma lista se publica como CREDITS.md y viaja con la carpeta.',
      cols: { icon: 'Ícono', use: 'Se usa para', creator: 'Autor', licence: 'Licencia', what: 'Qué' },

      licenceTitle: 'Licencia',
      licenceLead: 'El código es mío y lo puedo regalar. El arte no.',
      licence: {
        codeWhat: 'Las reglas, los datos de las cartas, las herramientas, el código del sitio y todo el texto',
        codeIs: 'MIT',
        artWhat: 'Los íconos de art/',
        artIs: 'CC BY, según la tabla de arriba',
        glyphsWhat: 'Los glifos dibujados en casa',
        glyphsIs: 'MIT, original',
      },
      licenceNote: 'Los autores dejan que cualquiera use estos dibujos con una sola condición: sus nombres van a donde vayan los dibujos. Si copias esta carpeta, eso te toca a ti.',
    },
    footer: { version: 'v0.1.0' },
    chrome: {
      subtitle: 'Equilibra tu ataque y tu defensa',
      skip: 'Saltar al contenido',
      sections: 'Secciones',
      closeDialog: 'Cerrar el diálogo',
      footerNote: 'Las reglas y las cartas son MIT. El arte de las cartas es CC BY, acreditado en la página Acerca de. Las partidas se guardan solo en este dispositivo.',
    },
    common: {
      loading: 'Cargando las cartas',
      loadFail: 'Los datos de las cartas no cargaron. Sirve la carpeta por HTTP (make serve) y recarga.',
      close: 'Cerrar',
      print: 'Imprimir',
      copied: 'Copiado',
      placeholder: 'arte provisorio',
      sayIt: 'Dilo en voz alta',
    },
    cards: {
      title: 'Las cartas',
      lead: 'Ciento once cartas, tamaño póker, sin una sola palabra impresa. Las esquinas llevan los números. El dibujo es el nombre, y decirlo en voz alta te toca a ti. Toca una carta para ver qué hace.',
      effect: {
        strike: 'Una acción, sin apostar nada: haces 25 de daño. Siempre acierta.',
        focus: 'Apuesta 1 carta de vida y tira Segura: 75 de daño. La carta queda De Lado, acierte o no.',
        'all-in': 'Dos acciones. Apuesta las cartas En Pie que quieras y tira Pareja: 100 por cada carta, o nada de nada.',
        bubble: 'Una acción y ninguna carta: absorbe los próximos 25 que te haga el jefe esta ronda. Sirve hasta en Furia.',
        run: 'Una acción: te Escondes hasta que el jefe actúe. Su Golpe pasa de largo; lo demás te llega a la mitad.',
        invention: 'Di tu hechizo en voz alta, apuesta 1 carta y tira Loca: acierta por 350, el número más grande del mazo.',
        slash: 'Apuesta 1 carta y tira Segura: 75 de daño. No tiene color propio: ataca con tu elemento.',
        ember: 'Apuesta 1 carta y tira Segura: 75 de daño como Fuego, la juegue quien la juegue.',
        torrent: 'Apuesta 1 carta y tira Segura: 75 de daño como Agua, la juegue quien la juegue.',
        tremor: 'Apuesta 1 carta y tira Segura: 75 de daño como Tierra, la juegue quien la juegue.',
        gale: 'Apuesta 1 carta y tira Segura: 75 de daño como Viento, la juegue quien la juegue.',
        piercer: 'Apuesta 1 carta y tira Segura: 100 de daño, atacando con tu elemento.',
        firebolt: 'Apuesta 1 carta y tira Segura: 100 de daño como Fuego.',
        'ice-spear': 'Solo el Mago. Apuesta 1 carta y tira Segura: 100 de daño como Agua.',
        boulder: 'Apuesta 1 carta y tira Segura: 100 de daño como Tierra.',
        cyclone: 'Apuesta 1 carta y tira Segura: 100 de daño como Viento.',
        'slash-wave': 'Solo el Caballero. Apuesta 2 cartas y tira Segura: 225 de daño, atacando con tu elemento.',
        nova: 'Apuesta 2 cartas y tira Segura: 225 de daño como Fuego.',
        'cold-curse': 'Apuesta 2 cartas y tira Segura: 225 de daño como Agua.',
        earthquake: 'Apuesta 2 cartas y tira Segura: 225 de daño como Tierra.',
        tempest: 'Apuesta 2 cartas y tira Segura: 225 de daño como Viento.',
        'soul-strike': 'Solo el Cazador. Apuesta 2 cartas y tira Pareja: 400 de daño, atacando con tu elemento.',
        pyre: 'Apuesta 2 cartas y tira Pareja: 400 de daño como Fuego.',
        maelstrom: 'Apuesta 2 cartas y tira Pareja: 400 de daño como Agua.',
        landslide: 'Apuesta 2 cartas y tira Pareja: 400 de daño como Tierra.',
        thunderhead: 'Apuesta 2 cartas y tira Pareja: 400 de daño como Viento.',
        meteor: 'Apuesta 3 cartas y tira Pareja: 750 de daño como Fuego.',
        deluge: 'Apuesta 3 cartas y tira Pareja: 750 de daño como Agua.',
        cataclysm: 'Apuesta 3 cartas y tira Pareja: 750 de daño como Tierra.',
        hurricane: 'Apuesta 3 cartas y tira Pareja: 750 de daño como Viento.',
        reaper: 'Solo el Nigromante. Apuesta 3 cartas y tira Pareja: 750 de daño, atacando con tu elemento.',
        taunt: 'Solo el Caballero. Una acción, sin apuesta: el jefe tira su dado ya, boca arriba, y sigues sabiendo qué viene.',
        knight: 'Una vez por ronda, defiende 25 de daño sin ninguna carta. Es una defensa, y la Furia la atraviesa derecho.',
        mage: 'Tu Puntería hace +25: 100 en vez de 75.',
        hunter: 'Una vez por ronda, vuelve a tirar una tirada fallada.',
        necromancer: 'Cuando cae un esbirro, toma una de sus cartas de vida como tuya, En Pie. En tus manos defiende 25.',
        cure: 'Devuelve 2 de tus cartas de vida Rotas a En Pie.',
        barrier: 'Cancela una acción del jefe por completo: lo que haya tirado, simplemente no pasa.',
        ally: 'Una figura compañera: le hace 25 gratis al jefe cada turno y atrae su Golpe lejos de ti. 50 de defensa.',
        rune: 'Una tirada de este nivel acierta automáticamente. Decláralo antes de tirar.',
        relic: 'Cada ataque que aciertes este nivel hace +25.',
        chest: 'Roba 2 cartas de Ventaja más.',
        'boss-s': 'El Esbirro: tamaño S, 2 cartas del jefe de 100, te hace 25 por ronda. Solo llega como Invocación, nunca pelea solo.',
        'boss-m': 'Tamaño M: 4 cartas de 100, Daño 50, Furia desde la ronda 4. Con un 1 hace Correteo: nada de daño, y tu próximo acierto hace +25.',
        'boss-l': 'Tamaño L: 7 cartas de 100, Daño 50, Furia desde la ronda 4. Con un 4 hace Enroscada: una Invocación cuyo esbirro golpea de inmediato.',
        'boss-l2': 'Tamaño L: 10 cartas de 100, Daño 75, Furia desde la ronda 4. Con un 1 hace Cimiento: Aguante, y se repara 25.',
        'boss-xl': 'Tamaño XL: 12 cartas de 100, Daño 100, Furia desde la ronda 4. Con un 6, Rompetormentas: Ruina, y otra vez si nada tuyo sigue En Pie.',
        'boss-um': 'Tamaño UM: 20 cartas de 100, Daño 100, Furia desde la ronda 5. Con un 5 hace Botín: te roba 1 carta de vida En Pie en vez de hacer daño.',
        volcano: 'Un lugar de Fuego: cada ataque de Fuego que acierte aquí hace +25.',
        river: 'Un lugar de Agua: cada ataque de Agua que acierte aquí hace +25.',
        mountain: 'Un lugar de Tierra: cada ataque de Tierra que acierte aquí hace +25.',
        desert: 'Un lugar de Viento: cada ataque de Viento que acierte aquí hace +25.',
        forest: 'Una vez por nivel, Esconderte no cuesta nada: ni carta ni acción. Hay dónde esconderse en todas partes.',
        village: 'Empiezas el nivel con 1 carta de vida En Pie extra.',
        castle: 'El jefe actúa dos veces en la ronda 1, y entre golpe y golpe tus cartas De Lado se Recuperan.',
        'life-fire': 'Vida de Fuego. Apuéstala para atacar; defiende con ella En Pie y vuelve; defiende con ella De Lado y se Rompe.',
        'life-water': 'Vida de Agua. Apuéstala para atacar; defiende con ella En Pie y vuelve; defiende con ella De Lado y se Rompe.',
        'life-earth': 'Vida de Tierra. Apuéstala para atacar; defiende con ella En Pie y vuelve; defiende con ella De Lado y se Rompe.',
        'life-wind': 'Vida de Viento. Apuéstala para atacar; defiende con ella En Pie y vuelve; defiende con ella De Lado y se Rompe.',
        'life-extra': 'Una carta de vida blanca, ganada al pasar cada nivel. Sin elemento; apuesta y defiende 25 como cualquiera.',
        'life-boss': 'Una carta del muro del jefe, vale 100. Haz 100 de daño y da vuelta una: la pila que se achica es su barra de vida.',
        'second-wind': 'Opcional. Cuando quedarías Caído, vuelve. Gratis una vez por nivel; después la tirada sube y el rescate se achica: 4 cartas, luego 3, luego 2, luego 1.',
        sidekick: 'Un segundo jugador es dueño de Golpe y Escape: esas acciones las elige, las dice y las tira él. La vida sigue compartida.',
        grudge: 'Cuando un jefe te derrota, ponla bajo su carta: la próxima pelea, una tirada que tú elijas acierta sola.',
        'aid-checks': 'Una referencia: los cuatro pasos de tirada y el número a igualar con cada dado, para que sirva el que tengas.',
        'aid-turn': 'Una referencia: la ronda en orden. Recupera, toma tus 3 acciones, golpean los esbirros, actúa el jefe.',
        'aid-boss': 'Una referencia: el dado que el jefe tira cada ronda. 1 Aguante, 2-3 Golpe, 4 Invocación, 5 Rugido, 6 Ruina.',
        'aid-breaks': 'Di a qué parte apuntaste y arráncasela: una Herida (50 menos), Lisiar (25 menos en todo lo que haga) o un Trofeo (una tirada gratis). Dos por jefe, y el adulto decide qué tan difícil es.',
      'aid-track': 'Un contador, no una regla: lleva el daño hecho en pasos de 25, con un dado que cuenta las centenas.',
      },
      printBtn: 'Imprimir',
      sheets: 'hojas',
      scopeLabel: 'Qué imprimir',
      scope: { all: 'Todo', essentials: 'Lo esencial', first: 'Primera partida' },
      scopeHint: {
        all: 'La caja completa.',
        essentials: 'Salta las 7 cartas de bioma: cualquier cosa sobre la mesa puede ser el lugar. Las de vida y de modo se quedan.',
        first: 'Todo lo que reparte la Primera partida: un jefe, seis cartas, la vida de los cuatro elementos y las ayudas.',
      },
      printDeck: 'Imprimir este mazo',
      printing: 'Armando la hoja de impresión',
      paper: 'Papel',
      a4: 'A4',
      // El tamaño de papel Letter se deja en inglés a propósito: "carta" ya es
      // la palabra para card en todo el resto de la interfaz.
      letter: 'Letter',
      backs: { _: 'Reversos', none: 'sin reversos', few: '4 reversos', all: 'un reverso por carta' },
      filterAll: 'Todos los mazos',
      copies: 'copias',
      deck: { attack: 'Ataque', skill: 'Habilidades', class: 'Clases', advantage: 'Ventaja', boss: 'Jefes', biome: 'Biomas', life: 'Vida', mode: 'Modo suave', aid: 'Ayudas' },
      val: { betAny: 'las cartas En Pie que quieras', none: 'ninguna', lifeCard: 'carta de vida', lifeCards: 'cartas de vida', xBet: '4 × lo que apuestes', classOnly: 'solamente' },
      corner: { bet: 'Apuesta', check: 'Tirada', tier: 'Rango', damage: 'Daño', actions: 'Acciones', element: 'Elemento', class: 'Clase', effect: 'Efecto', passive: 'Pasiva', size: 'Tamaño', life: 'Cartas de vida', rage: 'Furia desde la ronda', rule: 'Regla', value: 'Vale', copies: 'Copias', icon: 'Glifo' },
      check: { none: 'siempre acierta', sure: 'Segura, 75%', even: 'Pareja, 50%', hard: 'Difícil, 25%', wild: 'Loca, 15%' },
      step: { sure: 'Segura', even: 'Pareja', hard: 'Difícil', wild: 'Loca' },
      sort: { _: 'Ordenar por', deck: 'Mazo', element: 'Elemento', tier: 'Rango', class: 'Clase', check: 'Riesgo', damage: 'Daño', name: 'Nombre' },
      element: { _: 'Elemento', all: 'Cualquier elemento', none: 'El tuyo', fire: 'Fuego', water: 'Agua', earth: 'Tierra', wind: 'Viento' },
      tier: { _: 'Rango', all: 'Cualquier rango' },
      klass: { _: 'Clase', all: 'Cualquier clase', none: 'Para todas' },
      showBacks: 'Ver reversos',
      showFaces: 'Ver caras',
      reset: 'Limpiar filtros',
      empty: 'Ninguna carta calza con esos filtros.',
      face: 'Cara',
      back: 'Reverso',
      dlFace: 'Descargar la cara',
      dlBack: 'Descargar el reverso',
      dlFailed: 'Esa carta no se pudo exportar. Recarga y vuelve a intentarlo.',
      printOrder: 'La impresión siempre usa el orden de la caja, sin importar cómo esté ordenada esta lista.',
      // ── Los nombres de las cartas ────────────────────────────
      // Ninguna carta imprime su nombre: el nombre se dice en voz alta, así que
      // esta tabla es para gritarla. Va solo en `es`; en inglés manda
      // data/cards.json y cardName() cae ahí sola.
      name: {
        strike: 'Golpe', focus: 'Puntería', 'all-in': 'Todo o Nada', bubble: 'Burbuja', run: 'Escape',

        slash: 'Tajo', ember: 'Brasa', torrent: 'Torrente', tremor: 'Temblor', gale: 'Vendaval',
        piercer: 'Punzón', firebolt: 'Fogonazo', 'ice-spear': 'Lanza de Hielo', boulder: 'Peñasco', cyclone: 'Ciclón',
        'slash-wave': 'Onda Cortante', nova: 'Nova', 'cold-curse': 'Maldición Helada', earthquake: 'Terremoto', tempest: 'Tormenta',
        'soul-strike': 'Filo de Alma', pyre: 'Pira', maelstrom: 'Remolino', landslide: 'Derrumbe', thunderhead: 'Nubarrón',
        meteor: 'Meteoro', deluge: 'Diluvio', cataclysm: 'Cataclismo', hurricane: 'Huracán', reaper: 'Segador',

        knight: 'Caballero', mage: 'Mago', hunter: 'Cazador', necromancer: 'Nigromante',

        cure: 'Cura', barrier: 'Barrera', ally: 'Aliado', rune: 'Runa', relic: 'Reliquia', chest: 'Cofre',

        'boss-s': 'Esbirro', 'boss-m': 'Nivel 1', 'boss-l': 'Nivel 2', 'boss-l2': 'Nivel 3', 'boss-xl': 'Nivel 4', 'boss-um': 'Nivel 5',

        volcano: 'Volcán', river: 'Río', mountain: 'Montaña', desert: 'Desierto', forest: 'Bosque', village: 'Aldea', castle: 'Castillo',

        'life-fire': 'Fuego', 'life-water': 'Agua', 'life-earth': 'Tierra', 'life-wind': 'Viento', 'life-extra': 'Extra', 'life-boss': 'Jefe',

        'second-wind': 'Segundo Aire',
        invention: 'Invención',
        taunt: 'Provocación',
        sidekick: 'Compinche',
        grudge: 'Rencor',

        'aid-checks': 'Puente de Dados', 'aid-turn': 'Orden del Turno', 'aid-boss': 'Reacciones del Jefe', 'aid-track': 'Pista de Daño', 'aid-breaks': 'Roturas',
      },
    },
    learn: {
      heroKicker: 'Un desafío de jefes para imprimir y jugar, para un jugador',
      heroTitle: 'Equilibra tu <em>ataque</em> y tu <em>defensa</em>.',
      heroLead: 'Arma el jefe con bloques. Juega tu héroe como una figura. Las cartas que tienes delante son tu ataque y tu defensa al mismo tiempo: apostar sale gratis hasta que el jefe golpea y no te queda ninguna en pie. Un dado, ciento once cartas, y los juguetes que ya están en la mesa.',
      ctaPlay: 'Jugar en pantalla',
      ctaCards: 'Imprimir las cartas',
      ctaFirst: 'Primera Partida: un jefe, seis cartas',
      walkthroughKicker: 'Cómo se juega',
      rulebookTitle: 'El reglamento',
      rulebookLead: 'Las reglas completas, el mismo texto que viene con las cartas. Unos diez minutos de lectura.',
      rulebookFile: 'RULES.es.md',
      rulebookFail: 'RULES.es.md no cargó. Viene en el repositorio, al lado de esta página.',
      rulesRef: 'Regla ',
      bridgeTitle: 'Cualquier dado que tengas',
      bridgeLead: 'Busca tu fila. Tira. Iguala o supera el número. Tres d6 siguen a un d20 con no más de 1,2 puntos de diferencia en cada paso.',
      fidelityLead: 'La diferencia más grande entre lo que promete un paso y lo que da el dado:',
      fidelityUnit: 'puntos.',
      step: 'Paso',
      odds: 'Probabilidad',
      prev: 'Atrás',
      next: 'Siguiente',
      slideOf: 'de',
      contents: 'Contenido',
      deckHint: 'Usa las flechas, o desliza.',
      slide: { dice: 'Cualquier dado que tengas', rulebook: 'El reglamento', playNow: 'Pruébalo ahora mismo' },
      playNowKicker: 'Sin impresora',
      playNowTitle: 'Pruébalo ahora mismo',
      playNowLead: 'La pestaña Jugar tiene el juego entero en esta pantalla: las mismas cartas, un héroe provisorio y un jefe dibujado como si alguien lo hubiera armado. Prepararlo son cuatro elecciones rápidas. Cuando quieras la mesa de verdad, imprime las cartas y arma el jefe tú mismo.',
      playNowCta: 'Jugar la Primera Partida',
      playNowDesktop: 'Hecho para una pantalla de escritorio. En el teléfono sirve para una probada rápida.',
      ctaPlayNow: 'Pruébalo en pantalla ahora',
    },
    play: {
      title: 'Jugar',
      setupTitle: 'Prepara tu partida',
      quickRun: 'Partida rápida',
      quickRunLead: 'Tres jefes: el primero, el del medio y el último. Están achicados para que tres niveles cuenten la historia entera, y termines de verdad en una sola sentada.',
      kindWho: { first: 'Tu primera vez, o alguien nuevo en la mesa', quick: 'Quieres llegar al último jefe hoy', full: 'Una partida que dejas armada y retomas' },
      kindLevels: { first: 'un nivel', quick: 'tres niveles', full: 'cinco niveles' },
      kindMinutes: { first: '15 min', quick: '45 min', full: '2 h+' },
      firstGame: 'Primera Partida',
      firstGameLead: 'Solo el nivel 1, con Golpe, Puntería, Todo o Nada, Burbuja, Escape e Invención. Sin clases, sin habilidades, sin Ventaja. El juego entero ya está en esas seis cartas.',
      fullRun: 'Partida completa',
      fullRunLead: 'Cinco jefes. Clases después del primero, una habilidad nueva después de cada nivel, cartas de Ventaja por el camino.',
      element: 'Tu elemento',
      die: 'Tu dado',
      mode: 'Modo',
      story: 'Cuento', standard: 'Normal', nightmare: 'Pesadilla',
      modeHint: { story: 'un escalón más fácil, para una primera partida o un jugador más chico', standard: 'la tabla tal como se imprime', nightmare: 'un escalón más difícil' },
      start: 'Empezar',
      resume: 'Seguir la partida',
      abandon: 'Abandonar la partida',
      level: 'Nivel',
      round: 'Ronda',
      boss: 'Jefe',
      bossLife: 'Vida del jefe',
      hero: 'Tú',
      minion: 'Esbirro',
      ready: 'En Pie', spent: 'De Lado', broken: 'Rota',
      actionsLeft: 'acciones restantes',
      target: 'Objetivo',
      body: 'el jefe',
      bet: 'Apuesta',
      betHint: 'Elige cuántas cartas En Pie vas a apostar.',
      needActions: 'necesita 2 acciones y a tu turno le quedan menos',
      needBet: 'necesita una carta de vida En Pie para apostar',
      roll: 'Tirar',
      typeRoll: 'o escribe tu tirada',
      need: 'necesitas',
      hit: '¡Acierto!', miss: 'Fallo',
      endTurn: 'Terminar el turno',
      skipTurn: 'Pasar el turno',
      resolveAll: 'Resolver el resto',
      resolveAllHint: 'Tira todas las tiradas que quedan de una vez. El registro guarda cada una.',
      throw: 'Lanzar',
      damage: 'de daño',
      lands: 'acierta solo',
      bracedHalved: 'Aguante: a la mitad',
      rm: {
        lead: 'El plan está listo. Este turno tiene',
        check: 'tirada por hacer',
        checks: 'tiradas por hacer',
        noChecks: 'Todo acierta solo: no hay tiradas que hacer.',
        throw: 'Lanzar los dados',
        fast: 'Resolver todo de una',
        back: 'Volver al plan',
        close: 'Listo',
        next: 'Siguiente',
        step: 'Paso',
        of: 'de',
        throwHint: 'Un dado a la vez. Tú lanzas, lo ves caer, ves lo que hizo.',
        fastHint: 'Todas las tiradas de una vez. El registro guarda cada una.',
      },
      brk: {
        title: 'Romper una parte',
        say: 'Di a qué apuntaste y elige qué te da.',
        wound: 'Herida',
        woundHint: 'Pierde {n} al instante.',
        cripple: 'Lisiar',
        crippleHint: 'Todo lo que haga baja {n} el resto del nivel.',
        trophy: 'Trofeo',
        trophyHint: 'Una tirada de este nivel acierta sola.',
        left: 'partes quedan',
        none: 'A este ya no le quedan partes.',
        costs: 'cuesta una acción',
        free: 'concedido',
        held: 'La parte aguanta.',
        broke: '¡Se desprende!',
        cancel: 'Ahora no',
      },
      dm: {
        enable: 'Roturas',
        enableHint: 'Di a qué parte apuntaste y arráncasela: una Herida, Lisiar o un Trofeo. Apagado por defecto, porque el juego está completo sin esto. Enciéndelo cuando tu mesa quiera contar la pelea, no solo jugarla.',
        title: '¿Quién decide una rotura?',
        friendly: 'Amable',
        friendlyHint: 'Lo dices y pasa. Sin tirada y sin coste. Para la mesa más pequeña.',
        assisted: 'Asistido',
        assistedHint: 'Lo decide una tirada Difícil. El punto medio, y por donde empezar.',
        hardcore: 'Duro',
        hardcoreHint: 'Una tirada Loca, y cuesta una de tus tres acciones.',
        cap: 'Partes por jefe',
        capOff: 'Romper partes está apagado',
        edit: 'Cambiar los números',
        wound: 'Una Herida arranca',
        cripple: 'Lisiar quita',
      },
      levels5: '5 niveles',
      levelCleared: 'superado',
      outcome: { win: 'ganado', loss: 'perdido' },
      braceWhat: 'sin daño, y recibe la mitad el próximo turno',
      summonWhat: 'de su vida pasa bajo un esbirro',
      absorbed: 'absorbidos',
      oneAction: 'acción', manyActions: 'acciones', betAny: 'la que quieras',
      autoStep: 'auto',
      reorder: 'Drag to change the order',
      moveEarlier: 'Move earlier',
      moveLater: 'Move later',
      abandoned: 'Partida abandonada',
      drew: 'Robaste',
      castleAgain: 'Castillo: el jefe actúa de nuevo',
      bossThrow: 'Lanza el dado del jefe',
      bossThrown: 'El jefe sacó',
      bossOwnDie: 'o toca la cara que salió en tu d6',
      simpleMode: 'Mesa simple',
      simpleModeHint: 'Sin biomas y sin movimientos de firma: la tabla de reacciones y nada más. La forma de aprender el juego base antes de los extras.',
      takeIt: 'Recibirlo',
      go: 'Ir',
      finish: 'Terminar',
      outOfActions: 'Sin acciones. Termina el turno y el jefe actúa.',
      bossAskHow: '¿Tiraste un d6 de verdad? Toca la cara que salió. ¿Sin dado? El botón tira por ti.',
      tour: {
        wall: 'El muro de cartas es la vida del jefe. Cada 100 de daño tumba una carta; túmbalas todas y el nivel es tuyo.',
        life: 'Estas son tus cartas de vida. Apuéstalas para potenciar ataques, y mientras sigan en pie te defienden cuando el jefe golpea.',
        hand: 'Tu mano. Toca cartas para armar hasta tres acciones; pasa el mouse (o mantén presionado) para ver qué hace cada una.',
        go: 'Resolver tira tus tiradas. Cuando tu plan esté listo, Terminar el turno le pasa el dado al jefe.',
        next: 'Siguiente',
        skip: 'Saltar el paseo',
        done: 'Entendido',
      },
      firstWon: 'Ganaste la Primera Partida.',
      hist: { level: 'Nivel', result: 'Resultado', rounds: 'Rondas', broken: 'Rotas' },
      bossTurn: 'El jefe actúa',
      bossRoll: 'El jefe tira',
      hide: 'Esconderse', move: 'Mover',
      signatureName: { skitter: 'Correteo', coil: 'Enroscada', bedrock: 'Cimiento', stormbreak: 'Rompetormentas', hoard: 'Botín' },
      reactionName: { brace: 'Aguante', strike: 'Golpe', summon: 'Invocación', roar: 'Rugido', ruin: 'Ruina' },
      what: {
        strike: 'Siempre acierta. 25 de daño por una acción y ninguna carta.',
        focus: 'Apuesta una carta de vida. 75 de daño si sale la tirada Segura, y la carta se gasta igual.',
        'all-in': 'Apuesta las cartas En Pie que quieras: 100 por cada una, a cara o sello. Cuesta dos de tus tres acciones.',
        bubble: 'Absorbe los próximos 25 que recibas esta ronda. Solo vale una acción bajo Furia: fuera de Furia una carta En Pie te cubre gratis y vuelve, así que la Burbuja no te sirve de nada.',
        invention: 'Primero di el hechizo en voz alta: su nombre, cómo se ve, qué le hace a la sala. Apuesta una carta, tira la prueba Loca, y acierta por 350. El número más grande de tu mazo, detrás de la peor probabilidad.',
        run: 'Quedas Escondido hasta que el jefe actúe. Su Golpe pasa de largo y no te hace nada; todo lo demás igual te encuentra, pero solo por la mitad.',
      },
      hideHint: 'Gratis en el Bosque: quedas Escondido hasta que el jefe actúe.',
      hidden: 'Escondido',
      rage: 'Furia. Daño doble, sin defensa.',
      rageSoon: 'Furia la próxima ronda.',
      won: '¡El jefe cae!',
      lost: 'Estás Caído.',
      runWon: 'Pasaste los cinco niveles.',
      nextLevel: 'Siguiente nivel',
      newRun: 'Partida nueva',
      pickClass: 'Elige tu clase',
      draftTitle: 'Elige una habilidad',
      draftLead: 'Se destapan tres, te quedas con una.',
      advDraw: 'Robas una carta de Ventaja',
      advHand: 'Ventaja',
      playAdv: 'Jugar',
      useRune: 'Usar la Runa en esta tirada',
      reroll: 'Cazador: tira de nuevo',
      knight: 'Defensa de Caballero usada',
      barrierPrompt: '¿Juegas Barrera para cancelar esto?',
      letItHappen: 'Dejar que pase',
      log: 'Registro',
      logShow: 'Ver el registro', logHide: 'Ocultar el registro',
      // El jefe habla sobre su propia cabeza, no en el registro
      say: {
        hidden: 'No alcanza a ver adónde te fuiste.',
        allyNear: 'No le quita la vista al chico que está a tu lado.',
        minions: 'Los pequeños te dan vueltas alrededor.',
        bossHurt: 'Ya no se para derecho.',
        heroHurt: 'Se dio cuenta de que te tiemblan las manos.',
        braced: 'Se afirmó y te está esperando.',
        idle: [
          'El jefe te mira.',
          'El jefe no se ha movido. De alguna forma eso es peor.',
          'Algo se mueve dentro del montón, y se acomoda.',
          'Está decidiendo cuál de los dos parte.',
        ],
        events: {
          firstBlood: 'El primero entró. Eso lo sintió.',
          bigHit: 'Tembló la mesa entera. Todavía retumba.',
          whiff: 'Vio pasar ese golpe de largo. Se le nota el gusto.',
          revived: 'Te volviste a parar. No se lo esperaba.',
        },
        win: [
          'Se deshace, bloque por bloque.',
          'El muro ya no está. Lo que había detrás, tampoco.',
        ],
        loss: [
          'La mesa quedó en silencio. Vuelve a parar tus cartas: te espera.',
          'Caído, no terminado. La revancha empieza cuando tú digas.',
        ],
        bossIdle: {
          'boss-m': ['Te chasquea el caparazón.', 'Chico, rápido y muy seguro de sí mismo.'],
          'boss-l': ['Se enrosca, lento como la marea.', 'Ha ahogado héroes más valientes que tú.'],
          'boss-l2': ['Piedra que rechina contra piedra.', 'Lleva parado aquí más tiempo que tu casa.'],
          'boss-xl': ['El aire sabe a tormenta.', 'Sus alas tapan la lámpara.'],
          'boss-um': ['Cuenta sus cartas como monedas.', 'Todo lo que rompes, se lo queda.'],
        },
      },
      setup: {
        step1: 'Cómo van a jugar',
        step2: 'Quién eres',
        step3: 'Tu dado, y qué tan amable es el juego',
        step4: 'Prepara la mesa',
        next: 'Siguiente',
        back: 'Atrás',
        again: 'La misma mesa de la última vez',
        tableLead: 'La pantalla es el árbitro. La mesa es el juego. Antes de empezar:',
        tableSkip: '¿Solo probando en pantalla? No hay nada que armar: pulsa Empezar.',
        tableBoss: 'Arma el jefe con bloques. Hazlo más o menos del tamaño de su muro de cartas.',
        tableHero: 'Elige la figura de tu héroe y párala frente al jefe.',
        tableLife: 'Pon tus 4 cartas de vida paradas frente a ti, y ten tu dado a mano.',
        keys: 'Las flechas mueven entre opciones, Enter continúa.',
      },
      bossAsk: '¿Qué sacó el jefe?',
      bossRollFor: 'Tira por el jefe',
      abandonSure: '¿Seguro? Toca de nuevo para abandonar',
      undoLast: 'Deshacer',
      confirmKeep: 'Quedarse con',
      pickFirst: 'Toca una para elegirla',
      bossWatch: 'El jefe te mira.',
      aimedAtYou: 'apunta a ti',
      aimedAtAlly: 'apunta a tu Aliado',
      unguardable: 'no se puede defender',
      // La repisa: lo que ya tienes en juego
      shelf: 'En juego',
      relic: 'Reliquia', rune: 'Runa', bubbleSlot: 'Burbuja',
      // El número es ALLY_DEF en game/engine.js, no una palabra de acá: el
      // reglamento puede cambiarlo y este texto no tiene que salir a buscarse.
      ally: 'Aliado', allyDef: 'de defensa',
      allyGone: 'El Aliado se fue.',
      cover: 'Cubrir al Aliado',
      coverHint: 'Recibes el golpe tú, entero, y el Aliado se queda.',
      slotEmpty: 'vacío',
      // Las tres bandas del panel de acciones
      bandCards: 'Tus cartas', bandGo: 'Resolver',
      pickHint: 'el dado está esperando',
      placeholderNote: 'Los enemigos y los héroes son figuras provisorias hechas de bloques. El arte de verdad viene después.',
      // Segundo Aire, la carta del modo suave
      secondWind: 'Segundo Aire',
      secondWindHint: 'Una red de seguridad. La primera vuelta de cada nivel es gratis y te levanta del todo, después la tirada sube y el rescate se achica: 4 cartas, luego 3, luego 2, luego 1.',
      down: 'Estás Caído',
      downFree: 'Tu primera vuelta de este nivel es gratis.',
      downLadder: 'La vuelta pide',
      reviveTry: 'Intentar la vuelta',
      reviveGiveUp: 'Dejar que termine el nivel',
      // El carril del plan
      plan: 'Tu turno',
      planHint: 'Haz clic en una carta una vez por cada acción que quieras darle. Haz clic en un número para sacar ese paso.',
      planEmpty: 'Elige una carta. Tres acciones este turno.',
      resolvePlan: 'Resolver el turno',
      clearPlan: 'Limpiar',
      planStep: 'Paso',
      reaction: 'Reacción',
      reactionHint: 'Barrera espera acá a que el jefe actúe.',
      attachTo: 'unida al paso',
      tooManyActions: 'Eso es más que las acciones que quedan este turno.',
      notEnoughReady: 'Para ese paso ya no queda ninguna carta En Pie que apostar.',
      keys: '1 a 9 eligen carta · Enter resuelve · Retroceso deshace',
      // El resto de la mesa, a la vista pero sin jugar
      table: 'En la mesa',
      drawPile: 'Habilidades',
      advPile: 'Ventaja',
      extraPile: 'Vidas extra',
      biomeCard: 'Bioma',
      bossPile: 'Vida del jefe',
      faceDown: 'boca abajo',
      inTheBox: 'en la caja',
    },
    balance: {
      title: 'Balance',
      lead: 'El mismo motor que usa el juego en pantalla, jugado miles de veces por cuatro jugadores de mentira. La tabla publicada en BALANCE.md sale de tools/sim.py con 20.000 peleas por celda; esta es para probar cosas.',
      trials: 'Peleas por celda',
      bonus: 'Bono de afinidad',
      run: 'Ejecutar',
      running: 'Ejecutando',
      stop: 'Detener',
      style: { turtle: 'tortuga', safe: 'prudente', adaptive: 'adaptativa', gamble: 'arriesgada' },
      fightsPerCell: 'peleas por celda', runCompletion: 'Partidas de cinco niveles completadas en la línea adaptativa', thisRun: 'Esta corrida', rulebookRules: 'reglas del reglamento', legacyRules: 'reglas antiguas de tools/sim.py', bonus: 'de bono', publishedCaption: 'Publicado: docs/BALANCE.md, tools/sim.py, semilla 7, sin bono, sin clases, sin Ventaja', adaptiveCol: 'adaptativa',
      cols: { level: 'Nivel', win: 'victorias', rounds: 'rondas', broken: 'rotas' },
      legacy: 'Calzar exactamente con tools/sim.py',
      legacyHint: 'Reproduce tres simplificaciones que hace el simulador de Python (Aguante nunca parte a la mitad, Invocación mueve 100 fijos, Rugido aplana la siguiente tirada a Pareja) para poder revisar su tabla. Apagado, el motor juega el reglamento.',
      advantage: 'Mazo de Ventaja',
      klass: 'Clase',
      none: 'ninguna',
    },
  },
};

/** The languages the interface has a full table for, in the order the toggle shows them. */
export const LANGS = ['en', 'es'];

let lang = 'en';
export function setLang(l) { if (STRINGS[l]) lang = l; }
export function getLang() { return lang; }

/** t('play.start') -> 'Start'. Missing keys return the key, loudly. */
export function t(path) {
  const v = path.split('.').reduce((o, k) => (o && o[k] !== undefined ? o[k] : undefined), STRINGS[lang]);
  return v === undefined ? `[${path}]` : v;
}

/**
 * The name a player says out loud for a card, in the current language.
 *
 * No card face prints its name, so this is a spoken label and nothing else. In
 * English it is data/cards.json's own `name`, which is why there is no English
 * name table to drift from it; in another language it is the overlay in that
 * language's `cards.name`, keyed by card id, falling back to the English name
 * so an untranslated card is still readable rather than a raw [key].
 */
/**
 * The five boss reactions as an id-to-name map for the current language. A
 * table, not a string, so it does not go through t(): t() is contracted to
 * return a STRING and tests/content.test.mjs enforces that by scanning every
 * call, which is a contract worth keeping rather than widening.
 */
/**
 * The boss's atmospheric lines for the current language. A table, not a string,
 * so it does not go through t(): t() is contracted to return a STRING and
 * tests/content.test.mjs enforces that by scanning every call.
 */
export function bossLines() {
  return STRINGS[lang]?.play?.say || STRINGS.en.play.say;
}

export function reactionNames() {
  return { ...(STRINGS[lang]?.play?.reactionName || STRINGS.en.play.reactionName) };
}

/**
 * The Break Points aid draws its own labels, and js/cards/face.js is shared with
 * the print path and the node tests, neither of which sets a language. So the
 * names travel in through opts, the same way the boss reaction names already do.
 */
export function breakNames() {
  const b = STRINGS[lang]?.play?.brk || STRINGS.en.play.brk;
  return { wound: b.wound, cripple: b.cripple, trophy: b.trophy };
}
export function dmNames() {
  const d = STRINGS[lang]?.play?.dm || STRINGS.en.play.dm;
  return { friendly: d.friendly, assisted: d.assisted, hardcore: d.hardcore };
}

/**
 * An element's name in the reader's language. RULES.es.md has said Fuego, Agua,
 * Tierra and Viento since it was written; the screen said Fire, Water, Earth and
 * Wind, because seven render sites each capitalised the raw id instead of asking.
 */
export function elementName(el) {
  if (!el) return '';
  const table = STRINGS[lang]?.cards?.element || STRINGS.en.cards.element;
  return table[el] || (el.charAt(0).toUpperCase() + el.slice(1));
}

export function cardName(card) {
  if (!card) return '';
  const table = STRINGS[lang]?.cards?.name;
  return (card.id && table?.[card.id]) || card.name || '';
}
