// ── Entry point ──────────────────────────────────────────────
// One module per page, chosen by <body data-page> (the pages are generated by
// scripts/pages.py). Kept under 50 lines: it only picks and starts the page.

const PAGES = {
  catalog: () => import('./pages/catalog.js'),
  mug: () => import('./pages/mug.js'),
  brand: () => import('./pages/brand.js'),
  community: () => import('./pages/community.js'),
  shelf: () => import('./pages/shelf.js'),
  profile: () => import('./pages/profile.js'),
  admin: () => import('./pages/admin.js'),
};

const load = PAGES[document.body.dataset.page];
if (load) {
  load()
    .then((page) => page.start())
    .catch((err) => {
      console.error(err);
      const main = document.getElementById('main');
      if (main) {
        main.insertAdjacentHTML(
          'afterbegin',
          '<div class="wrap"><div class="notice notice--warn" role="alert">This page could not start. Reload to try again.</div></div>',
        );
      }
    });
}
