// ── Build-prompt export ──────────────────────────────────────
// Generates the markdown that turns this session into a build order:
// recipe, stack with every ingredient's free tier + gotcha, cost
// expectations, known challenges, and constraints for the AI builder.

import { CATEGORIES } from './data-services.js';
import { RECIPES, FRONTENDS, TIERS } from './data-recipes.js';
import { state, activeCategories, currentPick, bundlerFor } from './state.js';
import { infraTotals, buildTokens, modelCosts, subscriptionPath, yearOneTotal, activeRules, activeExits } from './costmodel.js';
import { fmtUsd, fmtTokens } from './utils.js';

function stackLines() {
  const lines = [];
  for (const catKey of activeCategories()) {
    const cat = CATEGORIES[catKey];
    const pick = currentPick(catKey);
    if (!pick) {
      const b = bundlerFor(catKey);
      lines.push(`- **${cat.label}:** bundled with ${b ? b.name : 'another pick'}. No extra service or cost.`);
      continue;
    }
    if (pick.type === 'none') {
      lines.push(`- **${cat.label}:** skip: ${pick.gotcha}`);
      continue;
    }
    const bits = [`**${cat.label}:** ${pick.name}`];
    const meta = [];
    if (pick.free) meta.push(`free tier: ${pick.free}`);
    meta.push(`then ${pick.entry}`);
    if (pick.revshare) meta.push(`cut: ${pick.revshare}`);
    if (pick.exit) meta.push(`exit: ${pick.exit}`);
    bits.push(`(${meta.join(' · ')})`);
    bits.push(`watch out: ${pick.gotcha}`);
    lines.push('- ' + bits.join(' '));
  }
  return lines;
}

function exitLines() {
  const exits = activeExits();
  const hard = exits.filter(e => e.grade !== 'easy');
  if (!hard.length) return ['Every pick here exits easily: this stack does not lock you in.'];
  return hard.map(e => `- **${e.from}** (${e.grade}): ${e.note}`);
}

export function buildPrompt() {
  const recipe = RECIPES[state.recipe] || RECIPES.blank;
  const fe = FRONTENDS[state.frontend];
  const totals = infraTotals();
  const tokens = buildTokens();
  const models = modelCosts();
  const sub = subscriptionPath();
  const cheap = models[0];
  const quality = models.find(m => m.bestValue) || models[Math.floor(models.length / 2)];

  const tierRow = Object.keys(TIERS).map(k => `${TIERS[k].label} ${fmtUsd(totals[k])}/mo`).join(' · ');

  const lines = [
    `# Build a ${recipe.label}: stack + constraints (Doorman recipe)`,
    '',
    `> ${recipe.blurb}`,
    '',
    '## Frontend approach',
    '',
    `**${fe.label}**: ${fe.blurb}`,
    ...fe.pros.map(p => `- + ${p}`),
    ...fe.cons.map(c => `- − ${c}`),
    '',
    '## The stack (swaps already decided: do not relitigate)',
    '',
    ...stackLines(),
    '',
    '## Cost expectations',
    '',
    `- **Infra:** ${tierRow} (estimates: confirm on each pricing page; prices researched July 2026).`,
    `- **AI build:** ~${fmtTokens(tokens)} tokens total → ~${fmtUsd(cheap.usd)} on ${cheap.name} (budget) or ~${fmtUsd(quality.usd)} on ${quality.name} (quality).`,
    `- **Subscription path:** one month of ${sub.plan} (~$${sub.usd}/mo) likely covers it, ${sub.note}`,
    `- **Year one, all-in:** ~${fmtUsd(yearOneTotal())} (12 months at Launched plus one ${quality.name} build).`,
    '',
    '## Known challenges (plan for these explicitly)',
    '',
    ...recipe.challenges.map((c, i) => `${i + 1}. **${c.title}**: ${c.note}`),
    '',
    '## What leaving costs (know the exits before moving in)',
    '',
    ...exitLines(),
    '',
    '## Constraints for the build',
    '',
    '- Start inside free tiers; call out exactly which limit gets hit first and when.',
    '- If a bundled pick (BaaS) covers a category, use it: do not add a second service for the same job.',
    '- Ship the smallest working version of the core loop first, then the secondary screens.',
    '- Every secret goes in env vars; every third-party call degrades gracefully.',
    '- No analytics or tracking beyond the chosen analytics pick.',
    '- Keep the data exportable: one command that dumps everything the app owns.',
    ...activeRules().map(r => `- [${r.from}] ${r.text}`),
    '',
    `_Generated by Doorman: doorman.neorgon.com_`,
  ];
  return lines.join('\n');
}

// ── Free-tier fit check ──────────────────────────────────────
// The second export: not a build order but a research order. Lists the
// stack's recorded free-tier limits plus the user's expected usage, and
// asks the agent to verify current limits and find the first one to break.

function usageLine(label, v, unit) {
  const n = Number(v);
  const shown = v !== '' && Number.isFinite(n) && n > 0
    ? `${n.toLocaleString('en-US')} ${unit}`
    : `[fill in: ${unit}]`;
  return `- **${label}:** ${shown}`;
}

function fitStackLines() {
  const lines = [];
  for (const catKey of activeCategories()) {
    const cat = CATEGORIES[catKey];
    const pick = currentPick(catKey);
    if (!pick) {
      const b = bundlerFor(catKey);
      lines.push(`- **${cat.label}:** bundled into ${b ? b.name : 'another pick'}; check the bundler's limits once, not per category.`);
      continue;
    }
    if (pick.type === 'none') continue;
    const free = !pick.free ? 'no free tier'
      : pick.free.startsWith('No free tier') ? pick.free
      : `free tier: ${pick.free}`;
    const link = pick.url ? ` · ${pick.url}` : '';
    lines.push(`- **${cat.label}:** ${pick.name} (${free})${link}`);
  }
  return lines;
}

export function buildFitPrompt() {
  const recipe = RECIPES[state.recipe] || RECIPES.blank;
  const u = state.usage;

  const lines = [
    `# Free-tier fit check: ${recipe.label} (Doorman)`,
    '',
    '> Question: will this stack stay at $0/mo at the usage below, and if not, which limit breaks first?',
    '',
    '## Expected usage (steady state, not launch-day spike)',
    '',
    usageLine('Visitors', u.visitors, 'visitors/month'),
    usageLine('Active users', u.users, 'monthly active users'),
    usageLine('Stored data', u.storageGb, 'GB total (files + database)'),
    '',
    'If a number above looks inconsistent with the app described, say so before calculating.',
    '',
    '## The stack to check',
    '',
    ...fitStackLines(),
    '',
    '## What to do',
    '',
    '1. Verify every free-tier limit on the linked pricing page. The limits quoted above were researched July 2026 and may have changed.',
    '2. Translate the expected usage into each service\'s own metering unit (MAU, function calls, bandwidth, build minutes, emails/day, records, message fan-out). State the assumptions behind each conversion.',
    '3. Flag the qualitative traps separately from the numbers: tiers that pause or sleep on inactivity, non-commercial-only clauses, card-required signups, and hard caps that stop service vs overages that bill automatically.',
    '4. Give a per-service verdict (fits / tight / will bill), then one overall verdict naming the FIRST limit to break and at what multiple of the expected usage it breaks.',
    '5. For anything that will bill, name the cheapest escape: that service\'s entry plan, or the swap this stack should make instead.',
    '',
    '## Output format',
    '',
    '| Service | Metered unit | Free limit | Projected usage | Headroom | Verdict |',
    '|---|---|---|---|---|---|',
    '',
    'Then a short verdict paragraph: the first limit to break, when, and what it costs to fix.',
    '',
    `_Generated by Doorman: doorman.neorgon.com_`,
  ];
  return lines.join('\n');
}
