// ── Holiday data ─────────────────────────────────────────────
// Public holidays ship with the site (data/holidays/<CC>.json, generated by
// tools/build-holidays.cjs from date-holidays). Nothing leaves the page: a
// country's file is fetched from this origin the first time a plan names it,
// then the plan re-renders. The lookup is what calendar.js consumes.

import { planRange, parseISO } from './calendar.js'

const files = new Map()      // code -> { years, tags } | 'loading' | 'failed'
let index = null             // [{ code, name }]
let onLoaded = () => {}

export const cal = {
  holidays(code, year) {
    const f = files.get(code)
    return f && typeof f === 'object' ? f.years[year] || [] : null
  },
  status(code) {
    const f = files.get(code)
    return !f ? 'none' : typeof f === 'string' ? f : 'ok'
  },
  /** 'often-worked' (a US federal holiday many private employers work), 'bridge' (a decreed non-working day), or ''. */
  tag(code, date) {
    const f = files.get(code)
    return (f && typeof f === 'object' && f.tags[date]) || ''
  },
}

/** What each tag means, for the chip's label and title. */
export const TAGS = {
  'often-worked': { label: 'often worked', many: 'often-worked days', title: 'A federal holiday that many private employers work' },
  bridge: { label: 'bridge day', many: 'bridge days', title: 'A non-working day set by decree: the public sector is off, private employers may work it' },
}

/** The dates with one tag that still cost a working day in this plan, for "work them all". */
export function taggedHolidays(doc, code, tag) {
  const s = doc.settings
  const range = planRange(s)
  if (!range) return []
  const worked = new Set((s.worked || []).filter(w => w.country === code).map(w => w.date))
  const out = []
  for (let y = range.from.getUTCFullYear(); y <= range.last.getUTCFullYear(); y++) {
    for (const [date] of cal.holidays(code, y) || []) {
      const d = parseISO(date)
      if (d && d >= range.from && d < range.to && (d.getUTCDay() || 7) <= s.daysPerWeek && !worked.has(date) && cal.tag(code, date) === tag) out.push(date)
    }
  }
  return out
}

/** Call once: the repaint to run whenever a calendar arrives. */
export function onHolidays(fn) { onLoaded = fn }

/** Fetch every calendar the plan needs that is not here yet. Safe to call on every render. */
export function ensureHolidays(codes) {
  for (const code of codes) {
    if (!code || files.has(code) || !/^[A-Z]{2}$/.test(code)) continue
    files.set(code, 'loading')
    fetch(`data/holidays/${code}.json`)
      .then(r => (r.ok ? r.json() : Promise.reject(new Error(r.status))))
      .then(d => { files.set(code, { years: d.years || {}, tags: d.tags || {} }) })
      .catch(() => { files.set(code, 'failed') })
      .finally(() => onLoaded())
  }
}

/** The country list for the pickers, loaded once. */
export async function loadIndex() {
  if (index) return index
  try {
    const r = await fetch('data/holidays/index.json')
    index = r.ok ? (await r.json()).countries : []
  } catch { index = [] }
  return index
}
export const countries = () => index || []

/** Pinned first in every picker, in this order: the teams Reparto is planned for. */
export const MAIN = ['US', 'CO', 'CL', 'PE', 'AR', 'MX']
const SHORT = { US: 'United States', GB: 'United Kingdom' }

export function countryName(code) {
  if (!code) return ''
  return SHORT[code] || countries().find(c => c.code === code)?.name || code
}
