// ── Lexicon ──────────────────────────────────────────────────
// One word pool per house theme. Callsign's own picks from public sources in
// the same vein as each manufacturer's in-game names. Every in-game proper
// name is left out on purpose; the test harness checks the pools against the
// real part list, and canon.js rerolls any designation that lands on one.

const words = (s) => s.trim().split(/\s+/);
const lines = (s) => s.trim().split(/\s*\|\s*/);

// BAWS: pen names from the wider circle of Basho's school. The Ten Disciples
// the game uses (and Basho himself) are left out; Shiko is the one it skipped.
export const POETS = words(`
  SHIKO SORA BONCHO OTOKUNI CHIGETSU IZEN TOKOKU KAKEI ROTSU SHADO SHOHAKU
  ISSHO MASAHIDE KYOKUSUI UKO TORIN SODO SENNA RIYU DOHO RANRAN SOHA SONOME OTSUYU`);

// Balam: surnames of noted entomologists.
export const ENTOMOLOGISTS = words(`
  FABRE LATREILLE KIRBY SPENCE WESTWOOD BATES MERIAN SWAMMERDAM REAUMUR
  FABRICIUS MEIGEN BURMEISTER ERICHSON LACORDAIRE COMSTOCK RILEY WHEELER NABOKOV
  DOUBLEDAY HAGEN LECONTE MELSHEIMER PACKARD WALSH FORBES FERNALD SNODGRASS
  WIGGLESWORTH TILLYARD MACLEAY WILLISTON MICHENER EISNER DETHIER CARPENTER`);

// Dafeng: asterisms of the Purple Forbidden and Supreme Palace enclosures, in
// hyphenated pinyin. Guards, walls and weapons for weapons; offices and
// buildings for the inner parts, the way the game splits them.
export const ASTERISMS_GUARD = words(`
  TIAN-BANG LANG-JIANG LANG-WEI ZUO-YUAN YOU-YUAN CHANG-YUAN CONG-GUAN NEI-PING
  TIAN-ZHU BEI-DOU SI-FU LIU-JIA TIAN-YI TAI-YI`);
export const ASTERISMS_OFFICE = words(`
  CHUAN-SHE NEI-JIE TIAN-CHU NEI-CHU WEN-CHANG TIAN-CHUANG SHANG-SHU DA-LI
  JIU-QING SAN-GONG SAN-SHI TAI-ZUN XING-CHEN TAI-ZI YE-ZHE ZHU-SHI NU-SHI YU-NU
  BA-GU HUA-GAI WU-DI-ZUO BEI-JI YIN-DE TIAN-LI WU-ZHU-HOU`);
export const ASTERISMS = [...ASTERISMS_GUARD, ...ASTERISMS_OFFICE];

// Schneider: German bird names (umlauts written ue, oe), and for boosters a
// part of the bird.
export const BIRDS = words(`
  SPERBER HABICHT MILAN BUSSARD FALKE UHU KAUZ SPECHT AMSEL DROSSEL LERCHE
  SCHWALBE STORCH KORMORAN EISVOGEL ZAUNKOENIG PIROL WIEDEHOPF SEEADLER
  WANDERFALKE ROTMILAN TURMFALKE BAUMFALKE GOLDAMMER DOHLE ELSTER RABE SEGLER
  MOEWE SCHWAN FISCHADLER STEINADLER KIEBITZ BRACHVOGEL NEUNTOETER`);
export const PLUMAGE = words(`
  SCHWINGE FEDER SCHNABEL KRALLE STEISS SCHWANZ DAUNE KIEL SPIEGEL KROPF HAUBE
  SCHOPF GEFIEDER DECKFEDER HANDSCHWINGE ARMSCHWINGE`);

// Elcano: Spanish. Steadfast, fortified and early-light words for the body,
// weather for the weapons.
export const SPANISH_STEADY = words(`
  CONSTANCIA TENACIDAD ENTEREZA TEMPLANZA LEALTAD BRAVURA TESON AUDACIA MURALLA
  BALUARTE ALCAZAR TORREON ATALAYA CIUDADELA ALMENA CUMBRE ALBOR AMANECER
  MADRUGADA LUCERO ALBORADA CENTINELA VIGIA`);
export const SPANISH_WEATHER = words(`
  RELAMPAGO TORMENTA GRANIZO NEVADA BRUMA NIEBLA RAFAGA CICLON CHUBASCO AGUACERO
  GALERNA CEFIRO LEVANTE PONIENTE SIROCO CENTELLA ESCARCHA HELADA VENDAVAL
  BORRASCA RAYO TRONADA`);

// RaD: job descriptions for the 2000 scouts, heavy plant for the 3000
// construction rigs, courses of a meal for the 5000 combat frames.
export const RAD_SCOUT = lines(`
  LOOKOUT | SPOTTER | SURVEYOR | SIGNALMAN | LINEMAN | PROSPECTOR | SWEEPER |
  FETCHER | NIGHT WATCH | TRAIL GUIDE | ODD JOBBER | GOPHER | DOGSBODY | GRUNT`);
export const RAD_WORKS = lines(`
  BULLDOZER | BACKHOE | EXCAVATOR | PILEDRIVER | JACKHAMMER | STEAMROLLER |
  FORKLIFT | RIVETER | WELDER | SANDBLASTER | CEMENT MIXER | GRADER | DUMP TRUCK`);
export const RAD_COURSES = lines(`
  ENTREE | SORBET | DIGESTIF | CHEESE COURSE | PALATE CLEANSER | CANAPE |
  STARTER | SECOND HELPING | LEFTOVERS | PETIT FOUR | CHEF SPECIAL |
  TASTING MENU | DOGGY BAG | BREAD BASKET | AFTER DINNER MINT`);
export const RAD_BOOSTERS = lines(`
  PACKHORSE | JUMPSTART | BACKFIRE | KICKSTAND | OXCART | HOTFOOT | TAILWIND |
  24680 | 13579`);
// RaD weapons: idioms and job titles for things that go off.
export const RAD_IDIOMS = lines(`
  HOUSE CALL | LAST ORDERS | PARTY FAVOR | SMALL TALK | COLD OPEN | PLUS ONE |
  HAPPY HOUR | LOST CAUSE | GOOD NEIGHBOR | SPARE CHANGE | DEAD LETTER |
  HOUSEWARMING | LATE FEE | WAKE UP CALL | FRONT ROW | KIND REGARDS | BIG FINISH |
  SOFT LAUNCH | CLEAN SLATE | HOT TAKE | ICE BREAKER | GRAND OPENING |
  FAIR WARNING | OPEN HOUSE | DOOR PRIZE | PARTING GIFT | QUIET HOURS |
  BEDSIDE MANNER | SECOND OPINION | POTLUCK | SWAN SONG | BRIGHT SIDE |
  RAIN CHECK | FIELD TRIP | PEN PAL | GUEST LIST | WELCOME MAT | ENCORE |
  CURTAIN CALL | LAST DANCE | NO HARD FEELINGS | CHAPERONE | SOMMELIER |
  LIFEGUARD | BABYSITTER | NIGHTCAP`);

// Melinite: plain words that lean toward precious things and loud sounds.
export const MELINITE = lines(`
  RHODIUM | OSMIUM | PALLADIUM | PLATINUM | GARNET | TOPAZ | OPAL | SAPPHIRE |
  CAMEO | FILIGREE | HEIRLOOM | CROWN JEWEL | KEEPSAKE | SPLENDID | REGAL |
  OPULENT | GILDED | SOVEREIGN | HANDCLAP | DRUMROLL | FANFARE | CRESCENDO |
  TINNITUS | WHISTLER | DAWN CHORUS | NIGHTINGALE | BELLRINGER | THUNDERCLAP |
  HUBBUB | GIDDY | WOOZY | TIPSY | SWOON`);

// ALLMIND: frames are a word for the mind plus a Greek letter; weapons are
// English words with their vowels stripped.
export const MINDWORDS = words(`
  NOUS SENSE WILL WITS NERVE FOCUS DREAM GAZE HUNCH INSIGHT INSTINCT REFLEX
  PSYCHE REASON THOUGHT`);
export const TERSE = words(`
  HARBOR BEACON COMPASS LANTERN LEDGER ARCHIVE SENTINEL WARDEN MIRROR CIPHER
  VECTOR SIGNAL CANOPY RAMPART TALON HALBERD SABER LANCE RAPIER GLAIVE SPEAR
  TRIDENT BALLISTA CATAPULT BULWARK PALADIN HERALD MARSHAL CONSUL TRIBUNE
  PRAETOR LEGATE CENSOR NOMAD BASTION CITADEL SPARROW FALCON TEMPEST`);
export const GREEK = words('ALPHA BETA GAMMA DELTA');

// Institute IA parts: biology for the body, sky and light for the weapons.
export const IA_BODY = words(`
  CORNEA RETINA CORTEX SYNAPSE AXON PLEXUS MARROW ATRIUM VENTRICLE CILIA FASCIA
  ALVEOLI LYMPH TENDON SINEW VERTEBRA ANTENNA MANDIBLE THORAX CHRYSALIS CARAPACE
  SPIRACLE PUPA LARVA NYMPH ELYTRA PROBOSCIS HALTERE CUTICLE CAPILLARY`);
export const IA_SKY = words(`
  ZENITH NADIR PARALLAX ECLIPTIC CORONA QUASAR PULSAR EQUINOX SOLSTICE UMBRA
  PENUMBRA APOGEE PERIGEE MERIDIAN BLUESHIFT HALO AZIMUTH AFTERGLOW MAGNETAR
  PERIHELION STARLIGHT SUNDOG TWILIGHT AIRGLOW SUPERNOVA COMET METEOR`);

// Institute IB codes the game already stamps, kept out of generated letters.
export const IB_TAKEN = words('HAL WLT NGI CEL SOL');
